# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/activemodel-serializers-xml/all/activemodel-serializers-xml.rbi
#
# activemodel-serializers-xml-1.0.2

module ActiveModel
end
module ActiveModel::Serializers
  extend ActiveSupport::Autoload
end
module ActiveModel::Serializers::Xml
  extend ActiveSupport::Concern
  include ActiveModel::Serialization
end
class ActiveModel::Serializers::Xml::Serializer
end
class ActiveModel::Serializers::Xml::Serializer::Attribute
end
class ActiveModel::Serializers::Xml::Serializer::MethodAttribute < ActiveModel::Serializers::Xml::Serializer::Attribute
end
module ActiveRecord
end
module ActiveRecord::Serialization
  include ActiveModel::Serializers::Xml
end
class ActiveRecord::XmlSerializer < ActiveModel::Serializers::Xml::Serializer
end
class ActiveRecord::XmlSerializer::Attribute < ActiveModel::Serializers::Xml::Serializer::Attribute
end
