# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/better_html/all/better_html.rbi
#
# better_html-1.0.16

module BetterHtml
end
class BetterHtml::InterpolatorError < RuntimeError
end
class BetterHtml::DontInterpolateHere < BetterHtml::InterpolatorError
end
class BetterHtml::UnsafeHtmlError < BetterHtml::InterpolatorError
end
class BetterHtml::HtmlError < RuntimeError
end
class BetterHtml::Errors < Array
end
module BetterHtml::Tokenizer
end
class BetterHtml::Tokenizer::Token
end
class BetterHtml::Tokenizer::Location < Parser::Source::Range
end
class BetterHtml::Tokenizer::BaseErb < Erubi::Engine
end
class BetterHtml::Tokenizer::JavascriptErb < BetterHtml::Tokenizer::BaseErb
end
class BetterHtml::Tokenizer::HtmlErb < BetterHtml::Tokenizer::BaseErb
end
class BetterHtml::Tokenizer::HtmlLodash
end
class BetterHtml::Tokenizer::TokenArray
end
module BetterHtml::AST
end
class BetterHtml::AST::Iterator
end
class BetterHtml::AST::Node < AST::Node
end
class BetterHtml::Parser
end
class BetterHtml::Parser::Error < BetterHtml::HtmlError
end
class BetterHtml::Config
  extend SmartProperties::ClassMethods
  include Anonymous_Module_60
  include SmartProperties
end
module Anonymous_Module_60
end
module BetterHtml::Helpers
end
class BetterHtml::HtmlAttributes
end
class BetterHtml::BetterErb
end
module BetterHtml::BetterErb::RuntimeChecks
end
class BetterHtml::BetterErb::ErubiImplementation < ActionView::Template::Handlers::ERB::Erubi
  include BetterHtml::BetterErb::RuntimeChecks
end
class BetterHtml::BetterErb::ValidatedOutputBuffer
end
class BetterHtml::BetterErb::ValidatedOutputBuffer::Context
end
module BetterHtml::BetterErb::ConditionalImplementation
end
class BetterHtml::Railtie < Rails::Railtie
end
