# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `bulma-rails` gem.
# Please instead update this file by running `bin/tapioca gem bulma-rails`.

module Bulma; end
class Bulma::Engine < ::Rails::Engine; end
