# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/capybara-screenshot/all/capybara-screenshot.rbi
#
# capybara-screenshot-1.0.26

class CapybaraScreenshot
end
module CapybaraScreenshot::Helpers
  extend CapybaraScreenshot::Helpers
end
module Capybara
end
module Capybara::Screenshot
end
module Capybara::Screenshot::Callbacks
end
class Capybara::Screenshot::Callbacks::CallbackSet < Array
end
module Capybara::Screenshot::Callbacks::ClassMethods
end
module Capybara::Screenshot::Callbacks::InstanceMethods
end
class Capybara::Screenshot::Saver
  extend Capybara::Screenshot::Callbacks::ClassMethods
  include Capybara::Screenshot::Callbacks
  include Capybara::Screenshot::Callbacks::InstanceMethods
end
module InvalidName___Class_0x00___ScreenshotOverrides_62
end
module Capybara::DSL
end
module Capybara::SessionScreenshotOverrides
end
class Capybara::Screenshot::Pruner
end
