# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/claide-plugins/all/claide-plugins.rbi
#
# claide-plugins-0.9.2

module CLAide
end
module CLAide::Plugins
  def self.config; end
  def self.config=(arg0); end
end
class CLAide::Plugins::Configuration
  def initialize(name = nil, plugin_prefix = nil, plugin_list_url = nil, plugin_template_url = nil); end
  def name; end
  def name=(arg0); end
  def plugin_list_url; end
  def plugin_list_url=(arg0); end
  def plugin_prefix; end
  def plugin_prefix=(arg0); end
  def plugin_template_url; end
  def plugin_template_url=(arg0); end
end
class CLAide::Command
end
class CLAide::Command::GemIndexCache
  def download_and_cache_specs; end
  def download_specs; end
  def flatten_fetcher_results(results); end
  def specs; end
  def specs_with_name(name); end
end
module CLAide::Command::GemHelper
  def self.cache; end
  def self.colorize_versions(versions); end
  def self.download_and_cache_specs; end
  def self.gem_installed?(gem_name, version_string = nil); end
  def self.installed_version(gem_name); end
  def self.versions_string(plugin_name, index_cache = nil); end
end
module CLAide::Command::PluginsHelper
  def self.download_json; end
  def self.known_plugins; end
  def self.matching_plugins(query, full_text_search); end
  def self.parse_json(json_str); end
  def self.plugin_prefix; end
  def self.plugin_title(plugin); end
  def self.plugins_raw_url; end
  def self.print_plugin(plugin, verbose = nil); end
  def self.print_verbose_plugin(plugin, ljust); end
end
class CLAide::Command::Plugins < CLAide::Command
end
class CLAide::Command::Plugins::List < CLAide::Command::Plugins
  def run; end
  def self.description; end
  def self.options; end
end
class CLAide::Command::Plugins::Search < CLAide::Command::Plugins
  def initialize(argv); end
  def run; end
  def self.options; end
  def validate!; end
end
module CLAide::Executable
  def executable(name); end
  def self.execute_command(exe, command, raise_on_failure); end
end
class CLAide::Executable::Indenter < Array
  def <<(value); end
  def indent; end
  def indent=(arg0); end
  def initialize(io = nil); end
  def io; end
  def io=(arg0); end
end
class CLAide::TemplateRunner
  def clone_template; end
  def configure_template; end
  def git!(*command); end
  def git(*command); end
  def initialize(name, template_url); end
  def template_repo_url; end
  extend CLAide::Executable
end
class CLAide::Command::Plugins::Create < CLAide::Command::Plugins
  def initialize(argv); end
  def run; end
  def self.description; end
  def show_reminder; end
  def validate!; end
end
class CLAide::PlainInformative < StandardError
end
class CLAide::Informative < CLAide::PlainInformative
end
