# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/code_analyzer/all/code_analyzer.rbi
#
# code_analyzer-0.5.5

module CodeAnalyzer
end
class CodeAnalyzer::Nil
end
class Sexp < Array
end
class CodeAnalyzer::Checker
end
class CodeAnalyzer::Warning
end
