# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/colored2/all/colored2.rbi
#
# colored2-3.1.2

module Colored2
  def self.background_next!; end
  def self.background_next?; end
  def self.decorate(a_class); end
  def self.disable!; end
  def self.enable!; end
  def self.foreground_next!; end
  def self.included(from_class); end
end
class Colored2::Code
  def escape; end
  def escape=(arg0); end
  def initialize(name); end
  def name; end
  def name=(arg0); end
  def to_s; end
  def value(shift = nil); end
end
class Colored2::Effect < Colored2::Code
  def codes; end
end
class Colored2::TextColor < Colored2::Code
  def codes; end
end
class Colored2::BackgroundColor < Colored2::TextColor
  def value; end
end
class Colored2::AsciiDecorator
  def decorate(options = nil); end
  def disable!(*args, **, &block); end
  def enable!(*args, **, &block); end
  def initialize(a_string); end
  def my_class; end
  def my_class=(arg0); end
  def no_color; end
  def self.__background_next; end
  def self.__background_next=(arg0); end
  def self.__colors_disabled; end
  def self.__colors_disabled=(arg0); end
  def self.background_next!; end
  def self.background_next?; end
  def self.disable!; end
  def self.enable!; end
  def self.enabled?; end
  def self.foreground_next!; end
  def string; end
  def string=(arg0); end
  def un_decorate; end
  extend Forwardable
end
class String
  def black!(string = nil, &block); end
  def black(string = nil, &block); end
  def blue!(string = nil, &block); end
  def blue(string = nil, &block); end
  def bold!(string = nil, &block); end
  def bold(string = nil, &block); end
  def cyan!(string = nil, &block); end
  def cyan(string = nil, &block); end
  def dark!(string = nil, &block); end
  def dark(string = nil, &block); end
  def green!(string = nil, &block); end
  def green(string = nil, &block); end
  def italic!(string = nil, &block); end
  def italic(string = nil, &block); end
  def magenta!(string = nil, &block); end
  def magenta(string = nil, &block); end
  def no_color!(string = nil, &block); end
  def no_color(string = nil, &block); end
  def normal!(string = nil, &block); end
  def normal(string = nil, &block); end
  def on; end
  def plain!(string = nil, &block); end
  def plain(string = nil, &block); end
  def red!(string = nil, &block); end
  def red(string = nil, &block); end
  def reversed!(string = nil, &block); end
  def reversed(string = nil, &block); end
  def surround_with_color(color: nil, effect: nil, color_self: nil, string: nil, &block); end
  def to_bol; end
  def to_eol; end
  def underlined!(string = nil, &block); end
  def underlined(string = nil, &block); end
  def white!(string = nil, &block); end
  def white(string = nil, &block); end
  def yellow!(string = nil, &block); end
  def yellow(string = nil, &block); end
  include Colored2
end
