# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/cork/all/cork.rbi
#
# cork-0.3.0

module Cork
end
class Cork::Board
  def ansi; end
  def ansi?; end
  def disable_wrap; end
  def disable_wrap=(arg0); end
  def disable_wrap?; end
  def err; end
  def gets; end
  def indentation_level; end
  def indentation_level=(arg0); end
  def info(message); end
  def initialize(verbose: nil, silent: nil, ansi: nil, input: nil, out: nil, err: nil); end
  def input; end
  def labeled(label, value, justification = nil); end
  def message(message, verbose_prefix = nil, relative_indentation = nil); end
  def notice(message); end
  def out; end
  def path(pathname, relative_to = nil); end
  def print(message); end
  def print_warnings; end
  def puts(message = nil); end
  def puts_indented(message = nil); end
  def puts_title(title, verbose_prefix); end
  def section(title, verbose_prefix = nil, relative_indentation = nil, titled = nil); end
  def silent; end
  def silent?; end
  def title(title, verbose_prefix = nil, relative_indentation = nil); end
  def title_level; end
  def title_level=(arg0); end
  def verbose; end
  def verbose?; end
  def warn(message, actions = nil, verbose_only = nil); end
  def warnings; end
  def wrap_string(string, indent = nil); end
end
module Cork::TextWrapper
  def self.strip_heredoc(string); end
  def self.word_wrap(line, line_width); end
  def self.wrap_formatted_text(string, indent = nil, width = nil); end
  def self.wrap_with_indent(string, indent = nil, width = nil); end
  def strip_heredoc(string); end
  def word_wrap(line, line_width); end
  def wrap_formatted_text(string, indent = nil, width = nil); end
  def wrap_with_indent(string, indent = nil, width = nil); end
end
