# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `danger-missed_localizable_strings` gem.
# Please instead update this file by running `bin/tapioca gem danger-missed_localizable_strings`.

# THIS IS AN EMPTY RBI FILE.
# see https://github.com/Shopify/tapioca/wiki/Manual-Gem-Requires
