# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `danger-rails_best_practices` gem.
# Please instead update this file by running `bin/tapioca gem danger-rails_best_practices`.

# THIS IS AN EMPTY RBI FILE.
# see https://github.com/Shopify/tapioca/wiki/Manual-Gem-Requires
