# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `dartsass-rails` gem.
# Please instead update this file by running `bin/tapioca gem dartsass-rails`.

module Dartsass; end
class Dartsass::Engine < ::Rails::Engine; end
Dartsass::VERSION = T.let(T.unsafe(nil), String)
