# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dartsass-rails/all/dartsass-rails.rbi
#
# dartsass-rails-0.3.0

module Dartsass
end
class Dartsass::Engine < Rails::Engine
end
