# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `debase` gem.
# Please instead update this file by running `bin/tapioca gem debase`.

module Debase
  private

  def breakpoints; end
  def catchpoints; end
  def contexts; end
  def current_context; end
  def debug_load(*_arg0); end
  def enable_file_filtering(_arg0); end
  def enable_trace_points; end
  def init_variables; end
  def prepare_context; end
  def remove_tracepoints; end
  def set_trace_flag_to_iseq(_arg0); end
  def setup_tracepoints; end
  def started?; end
  def unset_iseq_flags(_arg0); end
  def verbose=(_arg0); end
  def verbose?; end

  class << self
    # @param file [String]
    # @param line [Fixnum]
    # @param expr [String]
    def add_breakpoint(file, line, expr = T.unsafe(nil)); end

    def add_catchpoint(exception); end
    def attached; end
    def attached=(_arg0); end

    # Returns the value of attribute breakpoints.
    def breakpoints; end

    def catchpoint_deleted_event; end
    def catchpoint_deleted_event=(_arg0); end
    def catchpoints; end
    def cleanup_backtrace(backtrace); end
    def clear_catchpoints; end
    def cli_debug; end
    def cli_debug=(_arg0); end
    def contexts; end
    def control_thread; end
    def control_thread=(_arg0); end

    # Returns the value of attribute current_context.
    def current_context; end

    def debug; end
    def debug_load(*_arg0); end
    def debug_program(options); end
    def debugger_memory_limit; end
    def debugger_memory_limit=(_arg0); end
    def enable_file_filtering(_arg0); end
    def enable_trace_points; end
    def evaluation_timeout; end
    def evaluation_timeout=(_arg0); end
    def file_filter; end
    def find_free_port(host); end

    # Returns the value of attribute handler.
    def handler; end

    # Sets the attribute handler
    #
    # @param value the value to set the attribute handler to.
    def handler=(_arg0); end

    def init_variables; end
    def inspect_time_limit; end
    def inspect_time_limit=(_arg0); end
    def interface; end
    def interrupt_last; end

    # possibly deprecated options
    def keep_frame_binding; end

    # possibly deprecated options
    def keep_frame_binding=(_arg0); end

    def key_value_mode; end
    def key_value_mode=(_arg0); end

    # call-seq:
    #   Debugger.last_interrupted -> context
    #
    # Returns last debugged context.
    def last_context; end

    def monkey_patch_prepend; end

    # @return [Boolean]
    def post_mortem?; end

    def prepare_context; end
    def prepare_debugger(options); end
    def print_debug(*args); end
    def print_greeting_msg(stream, host, port, debugger_name = T.unsafe(nil), socket_path = T.unsafe(nil)); end
    def remove_breakpoint(id); end
    def remove_catchpoint(exception); end
    def remove_tracepoints; end
    def run_prog_script; end
    def set_trace_flag_to_iseq(_arg0); end
    def setup_tracepoints; end

    # call-seq:
    #   Debase.skip { block } -> obj or nil
    #
    # The code inside of the block is escaped from the debugger.
    def skip; end

    def source_reload; end
    def start(options = T.unsafe(nil), &block); end
    def start_; end
    def start_control(host, port, notify_dispatcher); end
    def start_control_unix(socket_path, notify_dispatcher); end
    def start_server(host = T.unsafe(nil), port = T.unsafe(nil), notify_dispatcher = T.unsafe(nil)); end
    def start_server_unix(socket_path, notify_dispatcher = T.unsafe(nil)); end

    # @return [Boolean]
    def started?; end

    def stop; end
    def trace_to_s; end
    def trace_to_s=(_arg0); end

    # possibly deprecated options
    def tracing; end

    # possibly deprecated options
    def tracing=(_arg0); end

    def unset_iseq_flags(_arg0); end
    def value_as_nested_element; end
    def value_as_nested_element=(_arg0); end
    def verbose=(_arg0); end
    def verbose?; end
    def xml_debug; end
    def xml_debug=(_arg0); end

    private

    def _start_control_common(host, port, socket_path, notify_dispatcher); end
    def _start_server_common(host, port, socket_path, notify_dispatcher); end
    def notify_dispatcher_if_needed(host, port, need_notify); end
  end
end

class Debase::Breakpoint
  # @return [Breakpoint] a new instance of Breakpoint
  def initialize(_arg0, _arg1, _arg2); end

  # Returns the value of attribute enabled.
  def enabled; end

  # Sets the attribute enabled
  #
  # @param value the value to set the attribute enabled to.
  def enabled=(_arg0); end

  # Returns the value of attribute expr.
  def expr; end

  # Sets the attribute expr
  #
  # @param value the value to set the attribute expr to.
  def expr=(_arg0); end

  # Returns the value of attribute id.
  def id; end

  # Returns the value of attribute pos.
  def pos; end

  # Returns the value of attribute source.
  def source; end

  class << self
    def find(_arg0, _arg1, _arg2, _arg3); end
    def remove(_arg0, _arg1); end
  end
end

class Debase::Context
  def at_breakpoint(breakpoint); end
  def at_catchpoint(excpt); end
  def at_line(file, line); end
  def at_return(file, line); end
  def at_tracing(file, line); end

  # @return [Boolean]
  def dead?; end

  def frame_args_info(frame_no = T.unsafe(nil)); end
  def frame_binding(*_arg0); end
  def frame_class(frame_no = T.unsafe(nil)); end
  def frame_file(*_arg0); end
  def frame_line(*_arg0); end
  def frame_locals(frame_no = T.unsafe(nil)); end
  def frame_self(*_arg0); end
  def handler; end

  # @return [Boolean]
  def ignored?; end

  def pause; end
  def stack_size; end
  def step(*_arg0); end
  def step_over(*_arg0); end
  def stop_frame=(_arg0); end
  def stop_next=(*_arg0); end
  def stop_reason; end

  # Returns the value of attribute thnum.
  def thnum; end

  # Returns the value of attribute thread.
  def thread; end
end

class Debase::DebugThread < ::Thread
  class << self
    # @private
    # @raise [RuntimeError]
    def inherited; end
  end
end

Debase::FRONT_END = T.let(T.unsafe(nil), String)

class Debase::FileFilter
  # @return [FileFilter] a new instance of FileFilter
  def initialize; end

  # @return [Boolean]
  def accept?(file_path); end

  def disable; end
  def enable; end
  def exclude(file_path); end
  def include(file_path); end

  private

  def excluded; end
  def included; end
end

Debase::IDE_VERSION = T.let(T.unsafe(nil), String)
Debase::VERSION = T.let(T.unsafe(nil), String)
Debugger = Debase
