# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/devise-i18n/all/devise-i18n.rbi
#
# devise-i18n-1.10.2

module DeviseI18n
end
class DeviseI18n::Engine < Rails::Engine
end
class DeviseI18n::Railtie < Rails::Railtie
  def self.add(pattern); end
  def self.pattern_from(args); end
end
