# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `dotenv_validator` gem.
# Please instead update this file by running `bin/tapioca gem dotenv_validator`.

# Knows how to check the environment variables and compares it to .env.sample
# and the comments in every line of your .env.sample file.
module DotenvValidator
  class << self
    # It analyzes the current environment and it compares it to the documentation
    # present in .env.sample.
    #
    # @return [[String], [String]] An array with two arrays. First array: List of missing variables. Second array: List of variables with invalid format.
    def analyze_variables; end

    # It checks the current environment and it returns a boolean value.
    #
    # @return [Boolean] True if everything looks good. False otherwise.
    def check; end

    # It checks the current environment and it raises a runtime exception.
    #
    # @raise [RuntimeError] Raised if a missing variable is found or an invalid format is encountered.
    def check!; end

    # It checks the value to check if it is an email or not.
    #
    # @param A [String] string
    # @return [Boolean] True if it is an email value. False otherwise.
    def email?(string); end

    # It checks the value to check if it is a float or not.
    #
    # @param A [String] string
    # @return [Boolean] True if it is a float value. False otherwise.
    def float?(string); end

    # It checks the value to check if it is an integer or not.
    #
    # @param A [String] string
    # @return [Boolean] True if it is an integer value. False otherwise.
    def integer?(string); end

    def open_sample_file; end

    # Internal: `Rails.root` is nil in Rails 4.1 before the application is
    # initialized, so this falls back to the `RAILS_ROOT` environment variable,
    # or the current working directory.
    #
    # Taken from Dotenv source code.
    def root; end

    def sample_file; end

    # It checks the value to check if it is a URL or not.
    #
    # @param A [String] string
    # @return [Boolean] True if it is an URL value. False otherwise.
    def url?(string); end
  end
end
