# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dotenv/all/dotenv.rbi
#
# dotenv-2.7.6

module Dotenv
end
module Dotenv::Substitutions
end
module Dotenv::Substitutions::Variable
end
module Dotenv::Substitutions::Command
end
class Dotenv::FormatError < SyntaxError
end
class Dotenv::Parser
end
class Dotenv::Environment < Hash
end
class Dotenv::Error < StandardError
end
class Dotenv::MissingKeys < Dotenv::Error
end
