# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dotenv_validator/all/dotenv_validator.rbi
#
# dotenv_validator-1.1.0

module DotenvValidator
  def self.analyze_variables; end
  def self.check!; end
  def self.check; end
  def self.email?(string); end
  def self.float?(string); end
  def self.integer?(string); end
  def self.open_sample_file; end
  def self.root; end
  def self.sample_file; end
  def self.url?(string); end
end
