# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ed25519/all/ed25519.rbi
#
# ed25519-1.3.0

module Ed25519
end
class Ed25519::SigningKey
end
class Ed25519::VerifyKey
end
class Ed25519::VerifyError < StandardError
end
class Ed25519::SelfTestFailure < StandardError
end
