# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/erubis/all/erubis.rbi
#
# erubis-2.7.0

module Erubis
end
class Erubis::TinyEruby
  def convert(input); end
  def evaluate(_context = nil); end
  def initialize(input = nil); end
  def result(_binding = nil); end
  def src; end
end
module Erubis::PI
end
class Erubis::PI::TinyEruby
  def convert(input); end
  def evaluate(_context = nil); end
  def initialize(input = nil, options = nil); end
  def result(_binding = nil); end
  def src; end
end
module Kernel
end
module Erubis::Generator
end
module Erubis::Converter
end
module Erubis::Basic
end
module Erubis::Basic::Converter
  include Erubis::Converter
end
module Erubis::PI::Converter
  include Erubis::Converter
end
class Erubis::ErubisError < StandardError
end
class Erubis::NotSupportedError < Erubis::ErubisError
end
class Erubis::Context
  include Enumerable
end
module Erubis::Evaluator
end
module Erubis::RubyEvaluator
  include Erubis::Evaluator
end
class Erubis::Engine
end
class Erubis::Basic::Engine < Erubis::Engine
  include Erubis::Basic::Converter
  include Erubis::Evaluator
  include Erubis::Generator
end
class Erubis::PI::Engine < Erubis::Engine
  include Erubis::Evaluator
  include Erubis::Generator
  include Erubis::PI::Converter
end
module Erubis::XmlHelper
end
module Erubis::EscapeEnhancer
end
module Erubis::StdoutEnhancer
end
module Erubis::PrintOutEnhancer
end
module Erubis::PrintEnabledEnhancer
end
module Erubis::ArrayEnhancer
end
module Erubis::ArrayBufferEnhancer
end
module Erubis::StringBufferEnhancer
end
module Erubis::StringIOEnhancer
end
module Erubis::ErboutEnhancer
end
module Erubis::NoTextEnhancer
end
module Erubis::NoCodeEnhancer
end
module Erubis::SimplifyEnhancer
end
module Erubis::BiPatternEnhancer
end
module Erubis::PrefixedLineEnhancer
end
module Erubis::PercentLineEnhancer
  include Erubis::PrefixedLineEnhancer
end
module Erubis::HeaderFooterEnhancer
end
module Erubis::DeleteIndentEnhancer
end
module Erubis::InterpolationEnhancer
end
module Erubis::RubyGenerator
  include Erubis::Generator
  include Erubis::StringBufferEnhancer
end
class Erubis::Eruby < Erubis::Basic::Engine
  include Erubis::RubyEvaluator
  include Erubis::RubyGenerator
end
class Erubis::FastEruby < Erubis::Eruby
  include Erubis::InterpolationEnhancer
end
class Erubis::EscapedEruby < Erubis::Eruby
  include Erubis::EscapeEnhancer
end
class Erubis::XmlEruby < Erubis::Eruby
  include Erubis::EscapeEnhancer
end
class Erubis::PI::Eruby < Erubis::PI::Engine
  include Erubis::RubyEvaluator
  include Erubis::RubyGenerator
end
