# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/factory_bot-awesome_linter/all/factory_bot-awesome_linter.rbi
#
# factory_bot-awesome_linter-1.0.5

module FactoryBot
end
class FactoryBot::AwesomeLinter
end
