# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `factory_bot-awesome_linter` gem.
# Please instead update this file by running `bin/tapioca gem factory_bot-awesome_linter`.

module FactoryBot
  extend ::FactoryBot::Syntax::Methods
  extend ::FactoryBot::Syntax::Default

  class << self
    # Returns the value of attribute aliases.
    def aliases; end

    # Sets the attribute aliases
    #
    # @param value the value to set the attribute aliases to.
    def aliases=(_arg0); end

    def aliases_for(attribute); end
    def automatically_define_enum_traits; end
    def automatically_define_enum_traits=(val); end

    # Set the starting value for ids when using the build_stubbed strategy
    #
    # Arguments:
    # * starting_id +Integer+
    #   The new starting id value.
    def build_stubbed_starting_id=(starting_id); end

    # An Array of strings specifying locations that should be searched for
    # factory definitions. By default, factory_bot will attempt to require
    # "factories", "test/factories" and "spec/factories". Only the first
    # existing file will be loaded.
    def definition_file_paths; end

    # An Array of strings specifying locations that should be searched for
    # factory definitions. By default, factory_bot will attempt to require
    # "factories", "test/factories" and "spec/factories". Only the first
    # existing file will be loaded.
    def definition_file_paths=(_arg0); end

    def factories(*_arg0, **_arg1, &_arg2); end
    def find_definitions; end

    # Look for errors in factories and (optionally) their traits.
    # Parameters:
    # factories - which factories to lint; omit for all factories
    # options:
    #   traits: true - to lint traits as well as factories
    #   strategy: :create - to specify the strategy for linting
    #   verbose: true - to include full backtraces for each linting error
    def lint(*args); end

    def register_strategy(*_arg0, **_arg1, &_arg2); end
    def reload; end
    def rewind_sequences(*_arg0, **_arg1, &_arg2); end
    def strategy_by_name(*_arg0, **_arg1, &_arg2); end
    def use_parent_strategy; end
    def use_parent_strategy=(val); end
  end
end

class FactoryBot::AwesomeLinter
  # @return [AwesomeLinter] a new instance of AwesomeLinter
  def initialize(*args, strategy: T.unsafe(nil), traits: T.unsafe(nil)); end

  def calculate_total; end
  def cleaning(&block); end

  # Returns the value of attribute factories_to_lint.
  def factories_to_lint; end

  # Returns the value of attribute invalid_factories.
  def invalid_factories; end

  def invalid_factory!(error, factory, trait = T.unsafe(nil)); end
  def lint!; end
  def lint_factory(factory); end
  def lint_trait(factory, trait); end
  def load_factories(*args); end
  def output_invalid_factories; end

  # Returns the value of attribute progress_bar.
  def progress_bar; end

  class << self
    def lint!(*args, **kwargs); end
  end
end

FactoryBot::Deprecation = T.let(T.unsafe(nil), ActiveSupport::Deprecation)
FactoryBot::VERSION = T.let(T.unsafe(nil), String)
