# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: ignore
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/friendly_id/all/friendly_id.rbi
#
# friendly_id-5.4.2

module FriendlyId
  def self.defaults(&block); end
  def self.extended(model_class); end
  def self.included(model_class); end
  def self.mark_as_unfriendly(klass); end
  def self.table_name_prefix; end
end
module FriendlyId::Base
  def friendly; end
  def friendly_id(base = nil, options = nil, &block); end
  def friendly_id_config; end
  def primary_key_type; end
end
module FriendlyId::Model
  def dup; end
  def friendly_id; end
  def friendly_id_config; end
  def self.included(model_class); end
  def to_param; end
end
module FriendlyId::ObjectUtils
  def friendly_id?; end
  def unfriendly_id?; end
end
module FriendlyId::UnfriendlyUtils
  def friendly_id?; end
  def unfriendly_id?; end
end
class Object < BasicObject
  include FriendlyId::ObjectUtils
end
class Array
  include FriendlyId::UnfriendlyUtils
end
class FalseClass
  include FriendlyId::UnfriendlyUtils
end
class Hash
  include FriendlyId::UnfriendlyUtils
end
class NilClass
  include FriendlyId::UnfriendlyUtils
end
class Numeric
  include FriendlyId::UnfriendlyUtils
end
class Symbol
  include FriendlyId::UnfriendlyUtils
end
class TrueClass
  include FriendlyId::UnfriendlyUtils
end
class FriendlyId::Configuration
  def base(*value); end
  def base=(arg0); end
  def defaults; end
  def dependent; end
  def dependent=(arg0); end
  def finder_methods; end
  def finder_methods=(arg0); end
  def get_module(object); end
  def initialize(model_class, values = nil); end
  def model_class; end
  def model_class=(arg0); end
  def modules; end
  def query_field; end
  def routes; end
  def routes=(arg0); end
  def set(values); end
  def use(*modules); end
  def uses?(mod); end
end
module FriendlyId::FinderMethods
  def exists?(conditions = nil); end
  def exists_by_friendly_id?(id); end
  def find(*args); end
  def find_by_friendly_id(id); end
  def first_by_friendly_id(id); end
  def parse_friendly_id(value); end
  def potential_primary_key?(id); end
  def raise_not_found_exception(id); end
end
module FriendlyId::Reserved
end
module FriendlyId::Reserved::Configuration
end
class FriendlyId::SlugGenerator
end
class FriendlyId::Candidates
  include Enumerable
end
module FriendlyId::Slugged
end
module FriendlyId::Slugged::Configuration
end
module FriendlyId::History
end
module FriendlyId::History::Configuration
end
module FriendlyId::History::FinderMethods
  include FriendlyId::FinderMethods
end
module FriendlyId::Slug::GeneratedAttributeMethods
end
class FriendlyId::Slug < ActiveRecord::Base
  extend Kaminari::ConfigurationMethods::ClassMethods
  include FriendlyId::Slug::GeneratedAssociationMethods
  include FriendlyId::Slug::GeneratedAttributeMethods
  include Kaminari::ActiveRecordModelExtension
  include Kaminari::ConfigurationMethods
end
module FriendlyId::Slug::GeneratedAssociationMethods
end
class FriendlyId::Slug::ActiveRecord_Relation < ActiveRecord::Relation
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include FriendlyId::Slug::GeneratedRelationMethods
end
module FriendlyId::Slug::GeneratedRelationMethods
end
class FriendlyId::Slug::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include FriendlyId::Slug::GeneratedRelationMethods
end
class FriendlyId::Slug::ActiveRecord_AssociationRelation < ActiveRecord::AssociationRelation
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include FriendlyId::Slug::GeneratedRelationMethods
end
class FriendlyId::Slug::ActiveRecord_DisableJoinsAssociationRelation < ActiveRecord::DisableJoinsAssociationRelation
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include FriendlyId::Slug::GeneratedRelationMethods
end
module FriendlyId::SimpleI18n
end
module FriendlyId::SimpleI18n::Model
end
module FriendlyId::SimpleI18n::Configuration
end
module FriendlyId::Scoped
end
module FriendlyId::Scoped::Configuration
end
module FriendlyId::Finders
end
module FriendlyId::Finders::ClassMethods
end
module FriendlyId::SequentiallySlugged
end
class FriendlyId::SequentiallySlugged::SequentialSlugCalculator
end
