# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/fuubar/all/fuubar.rbi
#
# fuubar-2.5.1

class Fuubar < RSpec::Core::Formatters::BaseTextFormatter
end
class Fuubar::Output < Delegator
end
