# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/gretel/all/gretel.rbi
#
# gretel-4.4.0

module Gretel
  def self.breadcrumb_paths; end
  def self.breadcrumb_paths=(paths); end
  def self.configure; end
  def self.register_style(style, options); end
  def self.reload_environments; end
  def self.reload_environments=(arg0); end
end
module Gretel::Resettable
  def reset!; end
end
module Gretel::Crumbs
  def self.breadcrumb_files; end
  def self.crumb_defined?(key); end
  def self.crumbs; end
  def self.load_breadcrumbs; end
  def self.loaded?; end
  def self.loaded_file_mtimes; end
  def self.reload?; end
  def self.reload_if_needed; end
end
class InvalidName___Class_0x00___Builder_49
  def crumb(key, &block); end
  def crumb_defined?(key); end
  def crumbs; end
  def initialize; end
end
class Gretel::Link
  def current!; end
  def current?; end
  def initialize(key, text, url, options = nil); end
  def key; end
  def key=(arg0); end
  def method_missing(method, *args, &block); end
  def options; end
  def options=(arg0); end
  def text; end
  def text=(arg0); end
  def url; end
  def url=(arg0); end
end
class Gretel::Crumb
  def context; end
  def initialize(context, key, *args); end
  def key; end
  def link(*args); end
  def links; end
  def method_missing(method, *args, **, &block); end
  def parent(*args); end
end
class Gretel::Renderer
  def breadcrumb_args; end
  def breadcrumb_key; end
  def context; end
  def initialize(context, breadcrumb_key, *breadcrumb_args); end
  def links; end
  def links_for_render(options = nil); end
  def method_missing(method, *args, &block); end
  def options_for_render(options = nil); end
  def options_for_style(style_key); end
  def parent_breadcrumb(options = nil); end
  def parent_links_for(crumb); end
  def render(options); end
  def self.register_style(style_key, options); end
  def self.styles; end
  def yield_parent_breadcrumb(options = nil); end
end
class Gretel::Renderer::LinkCollection < Array
  def context; end
  def html_safe?; end
  def initialize(context, links, options = nil); end
  def keys; end
  def links; end
  def options; end
  def render; end
  def structured_data(url_base:); end
  def to_s; end
end
class Gretel::Renderer::Base
  def breadcrumb_link_to(name, url, options = nil); end
  def context; end
  def fragment_options; end
  def fragment_tag; end
  def initialize(context, options); end
  def join_classes(*classes); end
  def method_missing(method, *args, &block); end
  def options; end
  def render_container(html); end
  def render_current_fragment(link, position); end
  def render_fragment(link, position); end
  def render_fragment_tag(fragment_tag, text, url, position, options = nil); end
  def render_posttext; end
  def render_pretext; end
end
class Gretel::Renderer::NonSemanticRenderer < Gretel::Renderer::Base
  def render_container(html); end
  def render_fragment_tag(fragment_tag, text, url, position, options = nil); end
end
class Gretel::Renderer::SemanticRenderer < Gretel::Renderer::Base
  def render_container(html); end
  def render_fragment_tag(fragment_tag, text, url, position, options = nil); end
end
module Gretel::ViewHelpers
  def breadcrumb(key = nil, *args); end
  def breadcrumbs(options = nil); end
  def gretel_renderer; end
  def parent_breadcrumb(options = nil, &block); end
  def with_breadcrumb(key, *args, &block); end
end
class Gretel::Railtie < Rails::Railtie
end
