# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `haml-rails` gem.
# Please instead update this file by running `bin/tapioca gem haml-rails`.

# The module that contains everything Haml-related:
#
# * {Haml::Parser} is Haml's parser.
# * {Haml::Compiler} is Haml's compiler.
# * {Haml::Engine} is the class used to render Haml within Ruby code.
# * {Haml::Options} is where Haml's runtime options are defined.
# * {Haml::Error} is raised when Haml encounters an error.
#
# Also see the {file:REFERENCE.md full Haml reference}.
module Haml
  class << self
    def init_rails(*args); end
  end
end

module Haml::Rails; end
class Haml::Rails::Engine < ::Rails::Engine; end
class Haml::Rails::Railtie < ::Rails::Railtie; end
Haml::VERSION = T.let(T.unsafe(nil), String)
