# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/highline/all/highline.rbi
#
# highline-2.0.3

class HighLine
  extend HighLine::BuiltinStyles::ClassMethods
  extend SingleForwardable
  include HighLine::BuiltinStyles
  include HighLine::CustomErrors
end
class HighLine::Terminal
end
module HighLine::CustomErrors
end
class HighLine::CustomErrors::ExplainableError < StandardError
end
class HighLine::CustomErrors::QuestionError < HighLine::CustomErrors::ExplainableError
end
class HighLine::CustomErrors::NotValidQuestionError < HighLine::CustomErrors::ExplainableError
end
class HighLine::CustomErrors::NotInRangeQuestionError < HighLine::CustomErrors::ExplainableError
end
class HighLine::CustomErrors::NoConfirmationQuestionError < HighLine::CustomErrors::ExplainableError
end
class HighLine::CustomErrors::NoAutoCompleteMatch < HighLine::CustomErrors::ExplainableError
end
class HighLine::Question
  include HighLine::CustomErrors
end
class HighLine::Question::AnswerConverter
  extend Forwardable
end
class HighLine::QuestionAsker
  include HighLine::CustomErrors
end
class HighLine::Menu < HighLine::Question
end
class HighLine::Menu::Item
end
class HighLine::ColorScheme
end
class HighLine::SampleColorScheme < HighLine::ColorScheme
end
class HighLine::Style
end
module HighLine::Wrapper
end
class HighLine::Paginator
end
class HighLine::TemplateRenderer
  extend Forwardable
end
class HighLine::Statement
end
class HighLine::List
end
class HighLine::ListRenderer
end
module HighLine::BuiltinStyles
end
module HighLine::BuiltinStyles::ClassMethods
end
class HighLine::Terminal::IOConsole < HighLine::Terminal
end
module HighLine::StringExtensions
end
class HighLine::String < String
  include HighLine::StringExtensions
end
