# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/hotwire-livereload/all/hotwire-livereload.rbi
#
# hotwire-livereload-1.1.0

module Hotwire
end
module Hotwire::Livereload
  def self.railtie_helpers_paths; end
  def self.railtie_namespace; end
  def self.railtie_routes_url_helpers(include_path_helpers = nil); end
  def self.table_name_prefix; end
  def self.use_relative_model_naming?; end
end
class Hotwire::Livereload::Engine < Rails::Engine
end
module Hotwire::Livereload::LivereloadTagsHelper
end
class Hotwire::Livereload::ReloadChannel < ActionCable::Channel::Base
end
