# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/html2haml/all/html2haml.rbi
#
# html2haml-2.2.0

module Html2haml
end
class Html2haml::HTML
end
class Html2haml::HTML::ERB < Erubis::Basic::Engine
end
module Nokogiri
end
module Nokogiri::XML
end
class Nokogiri::XML::Node
end
class Nokogiri::XML::Document < Nokogiri::XML::Node
end
class Nokogiri::XML::DocumentFragment < Nokogiri::XML::Node
end
class Nokogiri::XML::NodeSet
end
class Nokogiri::XML::ProcessingInstruction < Nokogiri::XML::Node
end
class Nokogiri::XML::CDATA < Nokogiri::XML::Text
end
class Nokogiri::XML::DTD < Nokogiri::XML::Node
end
class Nokogiri::XML::Comment < Nokogiri::XML::CharacterData
end
class Nokogiri::XML::Element < Nokogiri::XML::Node
end
