# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/i18n-spec/all/i18n-spec.rbi
#
# i18n-spec-0.6.0

module I18nSpec
end
module I18nSpec::FailureMessage
end
class I18nSpec::LocaleFile
end
