# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/i18n-tasks/all/i18n-tasks.rbi
#
# i18n-tasks-1.0.5

module I18n
end
module I18n::Tasks
end
class I18n::Tasks::CommandError < StandardError
end
module I18n::Tasks::SplitKey
end
module I18n::Tasks::KeyPatternMatching
  extend I18n::Tasks::KeyPatternMatching
end
module I18n::Tasks::Logging
end
module I18n::Tasks::PluralKeys
end
module I18n::Tasks::References
end
module I18n::Tasks::HtmlKeys
end
module I18n::Tasks::Scanners
end
module I18n::Tasks::Scanners::Results
end
class I18n::Tasks::Scanners::Results::Occurrence
end
class I18n::Tasks::Scanners::Results::KeyOccurrences
end
class I18n::Tasks::Scanners::Scanner
end
class I18n::Tasks::Scanners::FileScanner < I18n::Tasks::Scanners::Scanner
end
module I18n::Tasks::Scanners::RelativeKeys
end
module I18n::Tasks::Scanners::OccurrenceFromPosition
end
module I18n::Tasks::Scanners::RubyKeyLiterals
end
class I18n::Tasks::Scanners::PatternScanner < I18n::Tasks::Scanners::FileScanner
  include I18n::Tasks::Scanners::OccurrenceFromPosition
  include I18n::Tasks::Scanners::RelativeKeys
  include I18n::Tasks::Scanners::RubyKeyLiterals
end
class I18n::Tasks::Scanners::PatternWithScopeScanner < I18n::Tasks::Scanners::PatternScanner
end
class I18n::Tasks::Scanners::RubyAstCallFinder
  include AST::Processor::Mixin
end
class I18n::Tasks::Scanners::RubyAstScanner < I18n::Tasks::Scanners::FileScanner
  include AST::Sexp
  include I18n::Tasks::Scanners::RelativeKeys
end
class I18n::Tasks::Scanners::LocalRubyParser
end
class I18n::Tasks::Scanners::ErbAstProcessor
  include AST::Processor::Mixin
end
class I18n::Tasks::Scanners::ErbAstScanner < I18n::Tasks::Scanners::RubyAstScanner
end
class I18n::Tasks::Scanners::ScannerMultiplexer < I18n::Tasks::Scanners::Scanner
end
module I18n::Tasks::Concurrent
end
class I18n::Tasks::Concurrent::CachedValue
end
class I18n::Tasks::Concurrent::Cache
end
module I18n::Tasks::Scanners::Files
end
class I18n::Tasks::Scanners::Files::FileFinder
  include I18n::Tasks::Logging
end
class I18n::Tasks::Scanners::Files::CachingFileFinder < I18n::Tasks::Scanners::Files::FileFinder
end
class I18n::Tasks::Scanners::Files::CachingFileFinderProvider
end
class I18n::Tasks::Scanners::Files::FileReader
end
class I18n::Tasks::Scanners::Files::CachingFileReader < I18n::Tasks::Scanners::Files::FileReader
end
class I18n::Tasks::Scanners::PatternMapper < I18n::Tasks::Scanners::FileScanner
  include I18n::Tasks::Scanners::OccurrenceFromPosition
  include I18n::Tasks::Scanners::RelativeKeys
  include I18n::Tasks::Scanners::RubyKeyLiterals
end
module I18n::Tasks::UsedKeys
end
module I18n::Tasks::IgnoreKeys
end
module I18n::Tasks::MissingKeys
end
module I18n::Tasks::Interpolations
end
module I18n::Tasks::UnusedKeys
end
module I18n::Tasks::Translators
end
class I18n::Tasks::Translators::BaseTranslator
end
class I18n::Tasks::Translators::DeeplTranslator < I18n::Tasks::Translators::BaseTranslator
end
class I18n::Tasks::Translators::GoogleTranslator < I18n::Tasks::Translators::BaseTranslator
end
class I18n::Tasks::Translators::YandexTranslator < I18n::Tasks::Translators::BaseTranslator
end
module I18n::Tasks::Translation
end
module I18n::Tasks::LocalePathname
end
module I18n::Tasks::LocaleList
end
module I18n::Tasks::StringInterpolation
end
module I18n::Tasks::Data::Tree
end
module I18n::Tasks::Data::Tree::Traversal
end
class I18n::Tasks::Data::Tree::Nodes
  include Enumerable
  include I18n::Tasks::Data::Tree::Traversal
end
class I18n::Tasks::Data::Tree::Siblings < I18n::Tasks::Data::Tree::Nodes
  include I18n::Tasks::PluralKeys
  include I18n::Tasks::SplitKey
end
class I18n::Tasks::Data::Tree::Node
  include Enumerable
  include I18n::Tasks::Data::Tree::Traversal
end
module I18n::Tasks::Data::Router
end
class I18n::Tasks::Data::Router::PatternRouter
  include I18n::Tasks::KeyPatternMatching
end
class I18n::Tasks::Data::Router::ConservativeRouter < I18n::Tasks::Data::Router::PatternRouter
end
module I18n::Tasks::Data
end
module I18n::Tasks::Data::FileFormats
end
module I18n::Tasks::Data::FileFormats::ClassMethods
end
class I18n::Tasks::Data::FileSystemBase
  extend I18n::Tasks::Data::FileFormats::ClassMethods
  include I18n::Tasks::Data::FileFormats
  include I18n::Tasks::Logging
end
module I18n::Tasks::Data::Adapter
end
module I18n::Tasks::Data::Adapter::JsonAdapter
end
module I18n::Tasks::Data::Adapter::YamlAdapter
end
class I18n::Tasks::Data::FileSystem < I18n::Tasks::Data::FileSystemBase
end
module I18n::Tasks::Configuration
end
module I18n::Tasks::Stats
end
class I18n::Tasks::BaseTask
  include I18n::Tasks::Configuration
  include I18n::Tasks::Data
  include I18n::Tasks::HtmlKeys
  include I18n::Tasks::IgnoreKeys
  include I18n::Tasks::Interpolations
  include I18n::Tasks::KeyPatternMatching
  include I18n::Tasks::Logging
  include I18n::Tasks::MissingKeys
  include I18n::Tasks::PluralKeys
  include I18n::Tasks::References
  include I18n::Tasks::SplitKey
  include I18n::Tasks::Stats
  include I18n::Tasks::Translation
  include I18n::Tasks::UnusedKeys
  include I18n::Tasks::UsedKeys
end
