# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `i18n-spec` gem.
# Please instead update this file by running `bin/tapioca gem i18n-spec`.

module I18nSpec; end

module I18nSpec::FailureMessage
  def failure_for_should(&block); end
  def failure_for_should_not(&block); end
end

class I18nSpec::LocaleFile
  # @return [LocaleFile] a new instance of LocaleFile
  def initialize(filepath); end

  def content; end

  # Returns the value of attribute errors.
  def errors; end

  # Returns the value of attribute filepath.
  def filepath; end

  # Sets the attribute filepath
  #
  # @param value the value to set the attribute filepath to.
  def filepath=(_arg0); end

  def flattened_translations; end

  # @return [Boolean]
  def has_one_top_level_namespace?; end

  def invalid_pluralization_keys; end

  # @return [Boolean]
  def is_named_like_top_level_namespace?; end

  # @return [Boolean]
  def is_parseable?; end

  def locale; end
  def locale_code; end
  def missing_pluralization_keys; end
  def pluralizations; end
  def translations; end

  protected

  def flatten_tree(data, prefix = T.unsafe(nil), result = T.unsafe(nil)); end

  # @return [Boolean]
  def pluralization_data?(data); end

  def yaml_load_content; end
end

I18nSpec::LocaleFile::PLURALIZATION_KEYS = T.let(T.unsafe(nil), Array)
Psych::ParseError = Psych::SyntaxError
