# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `imagen` gem.
# Please instead update this file by running `bin/tapioca gem imagen`.

# Base module
module Imagen
  class << self
    def from_local(dir); end
    def from_remote(repo_url); end

    # Returns the value of attribute parser_version.
    def parser_version; end

    # Sets the attribute parser_version
    #
    # @param value the value to set the attribute parser_version to.
    def parser_version=(_arg0); end
  end
end

module Imagen::AST; end

# An AST Builder for ruby parser.
class Imagen::AST::Builder < ::Parser::Builders::Default
  # This is a work around for parsing ruby code that with invlalid UTF-8
  # https://github.com/whitequark/parser/issues/283
  def string_value(token); end
end

class Imagen::AST::Parser
  # @param parser_version [String] ruby syntax version
  # @return [Parser] a new instance of Parser
  def initialize(parser_version = T.unsafe(nil)); end

  def parse(input, file = T.unsafe(nil)); end
  def parse_file(filename); end
  def parser; end

  private

  # @raise [ArgumentError]
  def validate_version(parser_version); end

  class << self
    def parse(input, file = T.unsafe(nil)); end
    def parse_file(filename); end
  end
end

Imagen::AVAILABLE_RUBY_VERSIONS = T.let(T.unsafe(nil), Array)

# Responsible for cloning a Git repository into a given tempdir
class Imagen::Clone
  # @return [Clone] a new instance of Clone
  def initialize(repo_url, dirname); end

  # Returns the value of attribute dir.
  def dir; end

  def perform; end

  # Returns the value of attribute repo_url.
  def repo_url; end

  class << self
    def perform(repo_url, dir); end
  end
end

Imagen::EXCLUDE_RE = T.let(T.unsafe(nil), Regexp)

# Generic clone error
class Imagen::GitError < ::StandardError; end

module Imagen::Node; end

# Abstract base class
class Imagen::Node::Base
  # @return [Base] a new instance of Base
  def initialize; end

  # Returns the value of attribute ast_node.
  def ast_node; end

  def build_from_ast(ast_node); end

  # Returns the value of attribute children.
  def children; end

  def file_path; end
  def find_all(matcher, ret = T.unsafe(nil)); end
  def first_line; end

  # @raise [NotImplementedError]
  def human_name; end

  def last_line; end
  def line_numbers; end

  # Returns the value of attribute name.
  def name; end

  def source; end
  def source_lines; end
  def source_lines_with_numbers; end
end

# Represents a Ruby block
class Imagen::Node::Block < ::Imagen::Node::Base
  def build_from_ast(_ast_node); end
  def human_name; end

  private

  def args_list; end
end

# Represents a Ruby class method
class Imagen::Node::CMethod < ::Imagen::Node::Base
  def build_from_ast(ast_node); end
  def human_name; end
end

# Represents a Ruby class
class Imagen::Node::Class < ::Imagen::Node::Base
  def build_from_ast(ast_node); end
  def human_name; end
end

# Represents a Ruby instance method
class Imagen::Node::IMethod < ::Imagen::Node::Base
  def build_from_ast(ast_node); end
  def human_name; end
end

# Represents a Ruby module
class Imagen::Node::Module < ::Imagen::Node::Base
  def build_from_ast(ast_node); end
  def human_name; end
end

# Root node for a given directory
class Imagen::Node::Root < ::Imagen::Node::Base
  def build_from_dir(dir); end
  def build_from_file(path); end

  # Returns the value of attribute dir.
  def dir; end

  # TODO: fix wrong inheritance
  def file_path; end

  def first_line; end
  def human_name; end
  def last_line; end
  def source; end

  private

  def list_files; end
end

# RemoteBuilder is responsible for wrapping all operations to create code
# structure for a remote git repository.
class Imagen::RemoteBuilder
  # @return [RemoteBuilder] a new instance of RemoteBuilder
  def initialize(repo_url); end

  def build; end

  # Returns the value of attribute dir.
  def dir; end

  # Returns the value of attribute repo_url.
  def repo_url; end

  private

  def teardown; end
end

# AST Traversal that calls respective builder methods from Imagen::Node
class Imagen::Visitor
  # Returns the value of attribute current_root.
  def current_root; end

  # Returns the value of attribute file_path.
  def file_path; end

  # Returns the value of attribute root.
  def root; end

  def traverse(ast_node, parent); end

  # This method reeks of :reek:UtilityFunction
  def visit(ast_node, parent); end

  class << self
    def traverse(ast, root); end
  end
end

Imagen::Visitor::TYPES = T.let(T.unsafe(nil), Hash)
