# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/imagen/all/imagen.rbi
#
# imagen-0.1.8

module Imagen
end
module Imagen::AST
end
class Imagen::AST::Parser
end
class Imagen::AST::Builder < Parser::Builders::Default
end
module Imagen::Node
end
class Imagen::Node::Base
end
class Imagen::Node::Root < Imagen::Node::Base
end
class Imagen::Node::Module < Imagen::Node::Base
end
class Imagen::Node::Class < Imagen::Node::Base
end
class Imagen::Node::CMethod < Imagen::Node::Base
end
class Imagen::Node::IMethod < Imagen::Node::Base
end
class Imagen::Node::Block < Imagen::Node::Base
end
class Imagen::Visitor
end
class Imagen::GitError < StandardError
end
class Imagen::Clone
end
class Imagen::RemoteBuilder
end
