# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/iniparse/all/iniparse.rbi
#
# iniparse-1.5.0

module IniParse
end
class IniParse::Document
  include Enumerable
end
class IniParse::Generator
end
module IniParse::LineCollection
  include Enumerable
end
class IniParse::SectionCollection
  include IniParse::LineCollection
end
class IniParse::OptionCollection
  include IniParse::LineCollection
end
module IniParse::Lines
end
module IniParse::Lines::Line
end
class IniParse::Lines::Section
  include Enumerable
  include IniParse::Lines::Line
end
class IniParse::Lines::AnonymousSection < IniParse::Lines::Section
end
class IniParse::Lines::Option
  include IniParse::Lines::Line
end
class IniParse::Lines::Blank
  include IniParse::Lines::Line
end
class IniParse::Lines::Comment < IniParse::Lines::Blank
end
class IniParse::Parser
end
class IniParse::IniParseError < StandardError
end
class IniParse::ParseError < IniParse::IniParseError
end
class IniParse::NoSectionError < IniParse::ParseError
end
class IniParse::LineNotAllowed < IniParse::IniParseError
end
