# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/iso/all/iso.rbi
#
# iso-0.4.0

module ISO
end
class ISO::Tag
end
class ISO::Subtag
end
class ISO::Language < ISO::Subtag
end
class ISO::Region < ISO::Subtag
end
module ISO::UN
end
class ISO::UN::Region < ISO::Region
end
