# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `iso` gem.
# Please instead update this file by running `bin/tapioca gem iso`.

module ISO; end

class ISO::Language < ::ISO::Subtag
  # @return [Language] a new instance of Language
  def initialize(code, options = T.unsafe(nil)); end

  # Returns the value of attribute direction.
  def direction; end

  # Returns the value of attribute plural_rule_names.
  def plural_rule_names; end

  private

  def i18n_scope; end

  class << self
    def identify(full_code); end
  end
end

ISO::Language::DEFAULT_CODE = T.let(T.unsafe(nil), String)
ISO::Language::DEFAULT_DIRECTION = T.let(T.unsafe(nil), String)
ISO::Language::DEFAULT_PLURAL_RULE_NAMES = T.let(T.unsafe(nil), Array)
ISO::Language::DEFINITIONS_FILE = T.let(T.unsafe(nil), String)
ISO::Language::PLURAL_RULE_NAMES = T.let(T.unsafe(nil), Array)

class ISO::Region < ::ISO::Subtag
  private

  def i18n_scope; end

  class << self
    def identify(full_code); end
  end
end

ISO::Region::DEFINITIONS_FILE = T.let(T.unsafe(nil), String)

class ISO::Subtag
  # @return [Subtag] a new instance of Subtag
  def initialize(code, options = T.unsafe(nil)); end

  def ==(object); end

  # Returns the value of attribute code.
  def code; end

  def full_name; end
  def name; end

  private

  def i18n_scope; end

  class << self
    def all; end
    def codes; end
    def default; end
    def find(code); end
  end
end

class ISO::Tag
  # @return [Tag] a new instance of Tag
  def initialize(code); end

  def codes; end

  # Returns the value of attribute language.
  def language; end

  # Sets the attribute language
  #
  # @param value the value to set the attribute language to.
  def language=(_arg0); end

  # Returns the value of attribute region.
  def region; end

  # Sets the attribute region
  #
  # @param value the value to set the attribute region to.
  def region=(_arg0); end

  def subtags; end

  # @return [Boolean]
  def valid?; end
end

module ISO::UN; end

class ISO::UN::Region < ::ISO::Region
  # @return [Region] a new instance of Region
  def initialize(code, options = T.unsafe(nil)); end

  # Returns the value of attribute iso_code.
  def iso_code; end

  def name; end

  class << self
    def identify(full_code); end
  end
end

ISO::UN::Region::DEFINITIONS_FILE = T.let(T.unsafe(nil), String)
