# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/kaminari-activerecord/all/kaminari-activerecord.rbi
#
# kaminari-activerecord-1.2.2

module Kaminari
end
module Kaminari::Activerecord
end
module Kaminari::ActiveRecordRelationMethods
end
module Kaminari::PaginatableWithoutCount
end
module Kaminari::PaginatableWithoutCount::LimitValueSetter
end
module Kaminari::ActiveRecordModelExtension
  extend ActiveSupport::Concern
end
module Kaminari::ActiveRecordExtension
  extend ActiveSupport::Concern
end
module Kaminari::ActiveRecordExtension::ClassMethods
end
