# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/kwalify/all/kwalify.rbi
#
# kwalify-0.7.2

module Kwalify
  extend Kwalify::ErrorHelper
  extend Kwalify::Types
end
module Kwalify::Boolean
end
class TrueClass
  include Kwalify::Boolean
  include Kwalify::Scalar
end
class FalseClass
  include Kwalify::Boolean
  include Kwalify::Scalar
end
module Kwalify::Text
  include Kwalify::Scalar
end
class String
  include Kwalify::Scalar
  include Kwalify::Text
end
class Numeric
  include Kwalify::Scalar
  include Kwalify::Text
end
module Kwalify::Scalar
end
class Date
  include Kwalify::Scalar
end
class Time
  include Kwalify::Scalar
end
class NilClass
  include Kwalify::Scalar
end
module Kwalify::Types
end
class Kwalify::KwalifyError < StandardError
end
class Kwalify::AssertionError < Kwalify::KwalifyError
end
class Kwalify::BaseError < Kwalify::KwalifyError
end
class Kwalify::SchemaError < Kwalify::BaseError
end
class Kwalify::ValidationError < Kwalify::BaseError
end
class Kwalify::SyntaxError < Kwalify::BaseError
end
class Kwalify::YamlSyntaxError < Kwalify::SyntaxError
end
module Kwalify::ErrorHelper
end
class Kwalify::Rule
  include Kwalify::ErrorHelper
end
class Kwalify::Validator
  include Kwalify::ErrorHelper
end
module Kwalify::Util
end
class Kwalify::BaseParser
end
module Kwalify::Yaml
end
class Kwalify::Yaml::Parser < Kwalify::BaseParser
end
class Kwalify::MetaValidator < Kwalify::Validator
end
class Kwalify::PlainYamlParser
end
class Kwalify::PlainYamlParser::Alias
end
class Kwalify::YamlParser < Kwalify::PlainYamlParser
end
class Kwalify::Parser < Kwalify::YamlParser
end
module Kwalify::Json
end
