# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/mutations/all/mutations.rbi
#
# mutations-0.9.1

module Mutations
  def self.cache_constants=(val); end
  def self.cache_constants?; end
  def self.error_message_creator; end
  def self.error_message_creator=(creator); end
end
class Mutations::ValidationException < StandardError
  def errors; end
  def errors=(arg0); end
  def initialize(errors); end
  def to_s; end
end
class Mutations::DefaultErrorMessageCreator
  def message(key, error_symbol, options = nil); end
  def titleize(key); end
end
class Mutations::ErrorAtom
  def initialize(key, error_symbol, options = nil); end
  def message; end
  def message_list; end
  def symbolic; end
end
class Mutations::ErrorHash < Hash
  def message; end
  def message_list; end
  def symbolic; end
end
class Mutations::ErrorArray < Array
  def message; end
  def message_list; end
  def symbolic; end
end
class Mutations::InputFilter
  def default; end
  def discard_empty?; end
  def discard_invalid?; end
  def discard_nils?; end
  def filter(data); end
  def has_default?; end
  def initialize(opts = nil); end
  def options; end
  def options=(arg0); end
  def self.default_options; end
end
class Mutations::HashFilter < Mutations::InputFilter
  def array(name, options = nil, &block); end
  def boolean(name, options = nil, &block); end
  def date(name, options = nil, &block); end
  def duck(name, options = nil, &block); end
  def dup; end
  def file(name, options = nil, &block); end
  def filter(data); end
  def float(name, options = nil, &block); end
  def hash(name, options = nil, &block); end
  def initialize(opts = nil, &block); end
  def integer(name, options = nil, &block); end
  def model(name, options = nil); end
  def optional(&block); end
  def optional_inputs; end
  def optional_inputs=(arg0); end
  def optional_keys; end
  def required(&block); end
  def required_inputs; end
  def required_inputs=(arg0); end
  def required_keys; end
  def self.register_additional_filter(type_class, type_name); end
  def string(name, options = nil, &block); end
  def symbol(name, options = nil, &block); end
  def time(name, options = nil, &block); end
end
class Mutations::ArrayFilter < Mutations::InputFilter
  def array(options = nil, &block); end
  def boolean(options = nil, &block); end
  def date(options = nil, &block); end
  def duck(options = nil, &block); end
  def file(options = nil, &block); end
  def filter(data); end
  def filter_element(data); end
  def float(options = nil, &block); end
  def hash(options = nil, &block); end
  def initialize(name, opts = nil, &block); end
  def initialize_constants!; end
  def integer(options = nil, &block); end
  def model(name, options = nil); end
  def self.register_additional_filter(type_class, type_name); end
  def string(options = nil, &block); end
  def symbol(options = nil, &block); end
  def time(options = nil, &block); end
end
class Mutations::AdditionalFilter < Mutations::InputFilter
  def self.inherited(subclass); end
end
class Mutations::StringFilter < Mutations::AdditionalFilter
  def filter(data); end
end
class Mutations::IntegerFilter < Mutations::AdditionalFilter
  def filter(data); end
end
class Mutations::FloatFilter < Mutations::AdditionalFilter
  def filter(data); end
end
class Mutations::BooleanFilter < Mutations::AdditionalFilter
  def filter(data); end
end
class Mutations::DuckFilter < Mutations::AdditionalFilter
  def filter(data); end
end
class Mutations::DateFilter < Mutations::AdditionalFilter
  def filter(data); end
end
class Mutations::TimeFilter < Mutations::AdditionalFilter
  def filter(data); end
end
class Mutations::FileFilter < Mutations::AdditionalFilter
  def filter(data); end
end
class Mutations::ModelFilter < Mutations::InputFilter
  def filter(data); end
  def initialize(name, opts = nil); end
  def initialize_constants!; end
end
class Mutations::SymbolFilter < Mutations::AdditionalFilter
  def filter(data); end
end
class Mutations::Outcome
  def errors; end
  def initialize(is_success, result, errors, inputs); end
  def inputs; end
  def result; end
  def success?; end
end
class Mutations::Command
  def add_error(key, kind, message = nil); end
  def execute; end
  def has_errors?; end
  def initialize(*args); end
  def input_filters; end
  def inputs; end
  def merge_errors(hash); end
  def raw_inputs; end
  def run!; end
  def run; end
  def self.create_attr_methods(meth, &block); end
  def self.input_filters; end
  def self.optional(&block); end
  def self.required(&block); end
  def self.run!(*args); end
  def self.run(*args); end
  def self.validate(*args); end
  def validate; end
  def validation_outcome(result = nil); end
end
