# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/nap/all/nap.rbi
#
# nap-1.1.0

module REST
  def self.delete(uri, headers = nil, options = nil, &configure_block); end
  def self.get(uri, headers = nil, options = nil, &configure_block); end
  def self.head(uri, headers = nil, options = nil, &configure_block); end
  def self.patch(uri, body, headers = nil, options = nil, &configure_block); end
  def self.post(uri, body, headers = nil, options = nil, &configure_block); end
  def self.put(uri, body, headers = nil, options = nil, &configure_block); end
end
module REST::Error
end
module REST::Error::Timeout
  def self.class_names; end
  def self.classes; end
  def self.extend_classes!; end
  include REST::Error
end
module REST::Error::Connection
  def self.class_names; end
  def self.classes; end
  def self.extend_classes!; end
  include REST::Error
end
module REST::Error::Protocol
  def self.class_names; end
  def self.classes; end
  def self.extend_classes!; end
  include REST::Error
end
class Errno::ETIMEDOUT < SystemCallError
  include REST::Error::Timeout
end
class Timeout::Error < RuntimeError
  include REST::Error::Timeout
end
class Net::OpenTimeout < Timeout::Error
  include REST::Error::Timeout
end
class Net::ReadTimeout < Timeout::Error
  include REST::Error::Timeout
end
class EOFError < IOError
  include REST::Error::Connection
end
class Errno::ECONNABORTED < SystemCallError
  include REST::Error::Connection
end
class Errno::ECONNREFUSED < SystemCallError
  include REST::Error::Connection
end
class Errno::ECONNRESET < SystemCallError
  include REST::Error::Connection
end
class Errno::EHOSTDOWN < SystemCallError
  include REST::Error::Connection
end
class Errno::EHOSTUNREACH < SystemCallError
  include REST::Error::Connection
end
class Errno::EINVAL < SystemCallError
  include REST::Error::Connection
end
class Errno::ENETUNREACH < SystemCallError
  include REST::Error::Connection
end
class SocketError < StandardError
  include REST::Error::Connection
end
class OpenSSL::SSL::SSLError < OpenSSL::OpenSSLError
  include REST::Error::Connection
end
class Net::HTTPBadResponse < StandardError
  include REST::Error::Protocol
end
class Net::HTTPHeaderSyntaxError < StandardError
  include REST::Error::Protocol
end
class Net::ProtocolError < StandardError
  include REST::Error::Protocol
end
class Zlib::GzipFile::Error < Zlib::Error
  include REST::Error::Protocol
end
class REST::Request
  def body; end
  def body=(arg0); end
  def headers; end
  def headers=(arg0); end
  def http_proxy; end
  def http_request; end
  def initialize(verb, url, body = nil, headers = nil, options = nil, &configure_block); end
  def options; end
  def options=(arg0); end
  def path; end
  def perform; end
  def proxy_env; end
  def proxy_settings; end
  def request; end
  def request=(arg0); end
  def request_for_verb; end
  def self.perform(*args, &configure_block); end
  def url; end
  def url=(arg0); end
  def verb; end
  def verb=(arg0); end
end
class REST::Response
  def bad_request?; end
  def body; end
  def body=(arg0); end
  def created?; end
  def forbidden?; end
  def found?; end
  def headers; end
  def headers=(arg0); end
  def initialize(status_code, headers = nil, body = nil); end
  def internal_server_error?; end
  def moved_permanently?; end
  def not_found?; end
  def ok?; end
  def status_code; end
  def status_code=(arg0); end
  def success?; end
  def unauthorized?; end
  def unprocessable_entity?; end
end
