# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/nested_form/all/nested_form.rbi
#
# nested_form-0.3.2

module NestedForm
end
class NestedForm::Engine < Rails::Engine
end
module NestedForm::BuilderMixin
end
class NestedForm::Builder < ActionView::Helpers::FormBuilder
  include NestedForm::BuilderMixin
end
class NestedForm::SimpleBuilder < SimpleForm::FormBuilder
  include NestedForm::BuilderMixin
end
module NestedForm::ViewHelper
end
