# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/no_proxy_fix/all/no_proxy_fix.rbi
#
# no_proxy_fix-0.1.2

module NoProxyFix
end
