# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/overcommit/all/overcommit.rbi
#
# overcommit-0.58.0

module Overcommit
end
module Overcommit::OS
end
module Overcommit::Exceptions
end
class Overcommit::Exceptions::Error < StandardError
end
class Overcommit::Exceptions::ConfigurationError < Overcommit::Exceptions::Error
end
class Overcommit::Exceptions::ConfigurationSignatureChanged < Overcommit::Exceptions::Error
end
class Overcommit::Exceptions::GitConfigError < Overcommit::Exceptions::Error
end
class Overcommit::Exceptions::GitSubmoduleError < Overcommit::Exceptions::Error
end
class Overcommit::Exceptions::GitRevListError < Overcommit::Exceptions::Error
end
class Overcommit::Exceptions::HookSetupFailed < Overcommit::Exceptions::Error
end
class Overcommit::Exceptions::HookCleanupFailed < Overcommit::Exceptions::Error
end
class Overcommit::Exceptions::HookCancelled < Overcommit::Exceptions::Error
end
class Overcommit::Exceptions::HookLoadError < Overcommit::Exceptions::Error
end
class Overcommit::Exceptions::HookContextLoadError < Overcommit::Exceptions::Error
end
class Overcommit::Exceptions::InvalidCommandArgs < Overcommit::Exceptions::Error
end
class Overcommit::Exceptions::InvalidGitRepo < Overcommit::Exceptions::Error
end
class Overcommit::Exceptions::InvalidHookDefinition < Overcommit::Exceptions::Error
end
class Overcommit::Exceptions::InvalidHookSignature < Overcommit::Exceptions::Error
end
class Overcommit::Exceptions::MessageProcessingError < Overcommit::Exceptions::Error
end
class Overcommit::Exceptions::PreExistingHooks < Overcommit::Exceptions::Error
end
class Overcommit::Subprocess
end
module Overcommit::Utils
end
module Overcommit::Utils::FileUtils
end
class Overcommit::CommandSplitter
end
class Overcommit::Utils::Version < Gem::Version
end
class Overcommit::ConfigurationValidator
end
class Overcommit::Configuration
end
class Overcommit::ConfigurationLoader
end
class Overcommit::MessageProcessor
end
module Overcommit::Hook
end
class Overcommit::Hook::Base
  extend Forwardable
end
module Overcommit::HookContext
end
class Overcommit::HookContext::Base
end
module Overcommit::GitConfig
end
module Overcommit::GitRepo
end
class Overcommit::HookSigner
end
module Overcommit::HookLoader
end
class Overcommit::HookLoader::Base
end
class Overcommit::HookLoader::BuiltInHookLoader < Overcommit::HookLoader::Base
end
class Overcommit::HookLoader::PluginHookLoader < Overcommit::HookLoader::Base
end
class InterruptHandler
  extend Singleton::SingletonClassMethods
  include Singleton
end
class Overcommit::Printer
end
class Overcommit::HookRunner
end
class Overcommit::Installer
end
class Overcommit::Logger
end
