# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pagy/all/pagy.rbi
#
# pagy-5.10.1

class Pagy
  def count; end
  def from; end
  def in; end
  def initialize(vars); end
  def items; end
  def label; end
  def label_for(page); end
  def last; end
  def next; end
  def normalize_vars(vars); end
  def offset; end
  def page; end
  def pages; end
  def params; end
  def prev; end
  def self.root; end
  def series(size: nil, **_); end
  def setup_items_var; end
  def setup_offset_var; end
  def setup_pages_var; end
  def setup_params_var; end
  def setup_vars(name_min); end
  def to; end
  def vars; end
end
module Pagy::Backend
  def pagy(collection, vars = nil); end
  def pagy_get_items(collection, pagy); end
  def pagy_get_vars(collection, vars); end
end
module Pagy::UrlHelpers
  def pagy_deprecated_params(pagy, params); end
  def pagy_url_for(pagy, page, absolute: nil, html_escaped: nil); end
end
module Pagy::I18n
  def build(*locales); end
  def flatten(initial, prefix = nil); end
  def load(*locales); end
  def t(locale, key, opts = nil); end
  def translate(locale, key, opts = nil); end
  extend Pagy::I18n
end
module Pagy::I18n::P11n
end
module Pagy::Frontend
  def pagy_info(pagy, pagy_id: nil, item_name: nil, i18n_key: nil); end
  def pagy_link_proc(pagy, link_extra: nil); end
  def pagy_nav(pagy, pagy_id: nil, link_extra: nil, **vars); end
  def pagy_t(key, opts = nil); end
  include Pagy::UrlHelpers
end
class Pagy::VariableError < ArgumentError
  def initialize(pagy, variable, description, value); end
  def pagy; end
  def value; end
  def variable; end
end
class Pagy::OverflowError < Pagy::VariableError
end
class Pagy::I18nError < StandardError
end
class Pagy::InternalError < StandardError
end
class Pagy::Countless < Pagy
end
module Pagy::CountlessExtra
end
module Pagy::FrontendHelpers
end
module Pagy::FrontendHelpers::Pagy
end
module Pagy::FrontendHelpers::Calendar
end
module Pagy::FrontendHelpers::Frontend
end
module Pagy::BulmaExtra
end
