# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pry-rescue/all/pry-rescue.rbi
#
# pry-rescue-1.5.2

class PryRescue
end
class PryRescue::Rack
end
module PryRescue::SourceLocation
end
