# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rails_best_practices/all/rails_best_practices.rbi
#
# rails_best_practices-1.23.1

module RailsBestPractices
end
module RailsBestPractices::Core
end
class RailsBestPractices::Core::Check < CodeAnalyzer::Checker
end
module RailsBestPractices::Core::Check::Classable
end
module RailsBestPractices::Core::Check::Moduleable
end
module RailsBestPractices::Core::Check::Callable
end
module RailsBestPractices::Core::Check::InheritedResourcesable
end
module RailsBestPractices::Core::Check::Exceptable
end
module RailsBestPractices::Core::Check::Accessable
end
class RailsBestPractices::Core::ChecksLoader
end
class RailsBestPractices::Core::Configs < Hash
end
class RailsBestPractices::Core::Klasses < Array
end
class RailsBestPractices::Core::Klass
end
class RailsBestPractices::Core::Controllers < RailsBestPractices::Core::Klasses
end
class RailsBestPractices::Core::Error < CodeAnalyzer::Warning
end
class RailsBestPractices::Core::Gems < Array
end
class RailsBestPractices::Core::Gem
end
class RailsBestPractices::Core::Modules < Array
end
class RailsBestPractices::Core::Mod
end
class RailsBestPractices::Core::Helpers < RailsBestPractices::Core::Modules
end
class RailsBestPractices::Core::Mailers < RailsBestPractices::Core::Klasses
end
class RailsBestPractices::Core::Methods
end
class RailsBestPractices::Core::Method
end
class RailsBestPractices::Core::ModelAssociations
end
class RailsBestPractices::Core::ModelAttributes
end
class RailsBestPractices::Core::Models < RailsBestPractices::Core::Klasses
end
class RailsBestPractices::Core::Routes < Array
end
class RailsBestPractices::Core::Route
end
class RailsBestPractices::Core::Runner
end
module Erubis
end
class Erubis::OnlyRuby < Erubis::Eruby
end
class RailsBestPractices::Colorize
end
class RailsBestPractices::Analyzer
end
module RailsBestPractices::Lexicals
end
class RailsBestPractices::Lexicals::LongLineCheck < RailsBestPractices::Core::Check
end
class RailsBestPractices::Lexicals::RemoveTabCheck < RailsBestPractices::Core::Check
end
class RailsBestPractices::Lexicals::RemoveTrailingWhitespaceCheck < RailsBestPractices::Core::Check
end
module RailsBestPractices::Prepares
end
class RailsBestPractices::Prepares::ConfigPrepare < RailsBestPractices::Core::Check
end
class RailsBestPractices::Prepares::ControllerPrepare < RailsBestPractices::Core::Check
  include RailsBestPractices::Core::Check::Accessable
  include RailsBestPractices::Core::Check::Classable
  include RailsBestPractices::Core::Check::InheritedResourcesable
end
class RailsBestPractices::Prepares::GemfilePrepare < RailsBestPractices::Core::Check
end
class RailsBestPractices::Prepares::HelperPrepare < RailsBestPractices::Core::Check
  include RailsBestPractices::Core::Check::Accessable
  include RailsBestPractices::Core::Check::Moduleable
end
class RailsBestPractices::Prepares::InitializerPrepare < RailsBestPractices::Core::Check
end
class RailsBestPractices::Prepares::MailerPrepare < RailsBestPractices::Core::Check
  include RailsBestPractices::Core::Check::Classable
end
class RailsBestPractices::Prepares::ModelPrepare < RailsBestPractices::Core::Check
  include RailsBestPractices::Core::Check::Accessable
  include RailsBestPractices::Core::Check::Classable
end
class RailsBestPractices::Prepares::RoutePrepare < RailsBestPractices::Core::Check
end
class RailsBestPractices::Prepares::SchemaPrepare < RailsBestPractices::Core::Check
end
module RailsBestPractices::Reviews
end
class RailsBestPractices::Reviews::Review < RailsBestPractices::Core::Check
end
class RailsBestPractices::Reviews::AddModelVirtualAttributeReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::AlwaysAddDbIndexReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::CheckDestroyReturnValueReview < RailsBestPractices::Reviews::Review
  include RailsBestPractices::Core::Check::Classable
end
class RailsBestPractices::Reviews::CheckSaveReturnValueReview < RailsBestPractices::Reviews::Review
  include RailsBestPractices::Core::Check::Classable
end
class RailsBestPractices::Reviews::DefaultScopeIsEvilReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::DryBundlerInCapistranoReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::HashSyntaxReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::IsolateSeedDataReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::KeepFindersOnTheirOwnModelReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::LawOfDemeterReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::MoveCodeIntoControllerReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::MoveCodeIntoHelperReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::MoveCodeIntoModelReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::MoveFinderToNamedScopeReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::MoveModelLogicIntoModelReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::NeedlessDeepNestingReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::NotRescueExceptionReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::NotUseDefaultRouteReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::NotUseTimeAgoInWordsReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::OveruseRouteCustomizationsReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::ProtectMassAssignmentReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::RemoveEmptyHelpersReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::RemoveUnusedMethodsInControllersReview < RailsBestPractices::Reviews::Review
  include RailsBestPractices::Core::Check::Callable
  include RailsBestPractices::Core::Check::Classable
  include RailsBestPractices::Core::Check::Exceptable
  include RailsBestPractices::Core::Check::InheritedResourcesable
  include RailsBestPractices::Core::Check::Moduleable
end
class RailsBestPractices::Reviews::RemoveUnusedMethodsInHelpersReview < RailsBestPractices::Reviews::Review
  include RailsBestPractices::Core::Check::Callable
  include RailsBestPractices::Core::Check::Exceptable
  include RailsBestPractices::Core::Check::Moduleable
end
class RailsBestPractices::Reviews::RemoveUnusedMethodsInModelsReview < RailsBestPractices::Reviews::Review
  include RailsBestPractices::Core::Check::Callable
  include RailsBestPractices::Core::Check::Classable
  include RailsBestPractices::Core::Check::Exceptable
end
class RailsBestPractices::Reviews::ReplaceComplexCreationWithFactoryMethodReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::ReplaceInstanceVariableWithLocalVariableReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::RestrictAutoGeneratedRoutesReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::SimplifyRenderInControllersReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::SimplifyRenderInViewsReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::UseBeforeFilterReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::UseModelAssociationReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::UseMultipartAlternativeAsContentTypeOfEmailReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::UseObserverReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::UseParenthesesInMethodDefReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::UseQueryAttributeReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::UseSayWithTimeInMigrationsReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::UseScopeAccessReview < RailsBestPractices::Reviews::Review
end
class RailsBestPractices::Reviews::UseTurboSprocketsRails3Review < RailsBestPractices::Reviews::Review
end
module RailsBestPractices::InlineDisables
end
class RailsBestPractices::InlineDisables::CommentRipper < Ripper::SexpBuilder
end
class RailsBestPractices::InlineDisables::InlineDisable < RailsBestPractices::Core::Check
end
class RailsBestPractices::OptionParser
end
class RailsBestPractices::CLI
end
