# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `require_all` gem.
# Please instead update this file by running `bin/tapioca gem require_all`.

# THIS IS AN EMPTY RBI FILE.
# see https://github.com/Shopify/tapioca/wiki/Manual-Gem-Requires
