# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/require_all/all/require_all.rbi
#
# require_all-3.0.0

module RequireAll
end
class RequireAll::LoadError < LoadError
end
