# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/responders/all/responders.rbi
#
# responders-161f205b6494

module Responders
end
module Responders::ControllerMethod
  def responders(*responders); end
end
module ActionController
end
class Responders::Railtie < Rails::Railtie
end
module Responders::FlashResponder
end
class ActionController::Responder
end
module ActionController::RespondWith
  extend ActiveSupport::Concern
end
module ActionController::RespondWith::ClassMethods
end
