# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rspec_junit_formatter/all/rspec_junit_formatter.rbi
#
# rspec_junit_formatter-0.5.1

class RSpecJUnitFormatter < RSpec::Core::Formatters::BaseFormatter
end
