# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby-debug-ide` gem.
# Please instead update this file by running `bin/tapioca gem ruby-debug-ide`.

Debugger = Debase
