# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rugged/all/rugged.rbi
#
# rugged-1.0.1

module Rugged
end
class Rugged::Index
  include Enumerable
end
class Rugged::Object
end
class Rugged::Commit < Rugged::Object
end
class Rugged::Repository
end
class Rugged::Reference
end
class Rugged::Walker
  include Enumerable
end
class Rugged::Tree < Rugged::Object
  include Enumerable
end
class Rugged::Tag < Rugged::Reference
end
class Rugged::Tag::Annotation < Rugged::Object
end
class Rugged::Branch < Rugged::Reference
end
class Rugged::Diff
  include Enumerable
end
class Rugged::Diff::Hunk
end
class Rugged::Diff::Line
end
class Rugged::Diff::Delta
end
class Rugged::Patch
  include Enumerable
end
class Rugged::Remote
end
module Rugged::Credentials
end
class Rugged::Credentials::UserPassword
end
class Rugged::Credentials::SshKey
end
class Rugged::Credentials::SshKeyFromAgent
end
class Rugged::Credentials::Default
end
class Rugged::Repository::Attributes
  include Enumerable
end
class Rugged::Blob < Rugged::Object
end
class Rugged::Blob::HashSignature
end
class Rugged::SubmoduleCollection
end
