# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sassc/all/sassc.rbi
#
# sassc-2.4.0

module SassC
end
module SassC::Native
  extend FFI::Library
end
class SassC::Native::SassValue < FFI::Union
end
class SassC::Native::SassUnknown < FFI::Struct
end
class SassC::Native::SassBoolean < FFI::Struct
end
class SassC::Native::SassNumber < FFI::Struct
end
class SassC::Native::SassColor < FFI::Struct
end
class SassC::Native::SassString < FFI::Struct
end
class SassC::Native::SassList < FFI::Struct
end
class SassC::Native::SassMapPair < FFI::Struct
end
class SassC::Native::SassMap < FFI::Struct
end
class SassC::Native::SassNull < FFI::Struct
end
class SassC::Native::SassError < FFI::Struct
end
class SassC::Native::SassWarning < FFI::Struct
end
class SassC::Native::StringList < FFI::Struct
end
class SassC::ImportHandler
end
class SassC::Importer
end
class SassC::Importer::Import
end
module SassC::Util
  extend SassC::Util
end
class SassC::Util::NormalizedMap
end
module SassC::Script
end
class SassC::Script::Value
end
class SassC::Script::Value::Bool < SassC::Script::Value
end
class SassC::Script::Value::Number < SassC::Script::Value
end
class SassC::Script::Value::Color < SassC::Script::Value
end
class SassC::Script::Value::String < SassC::Script::Value
end
class SassC::Script::Value::List < SassC::Script::Value
end
class SassC::Script::Value::Map < SassC::Script::Value
end
module SassC::Script::Functions
end
module SassC::Script::ValueConversion
end
class SassC::Script::ValueConversion::Base
end
class SassC::Script::ValueConversion::String < SassC::Script::ValueConversion::Base
end
class SassC::Script::ValueConversion::Number < SassC::Script::ValueConversion::Base
end
class SassC::Script::ValueConversion::Color < SassC::Script::ValueConversion::Base
end
class SassC::Script::ValueConversion::Map < SassC::Script::ValueConversion::Base
end
class SassC::Script::ValueConversion::List < SassC::Script::ValueConversion::Base
end
class SassC::Script::ValueConversion::Bool < SassC::Script::ValueConversion::Base
end
class SassC::FunctionsHandler
end
class SassC::Dependency
end
class SassC::BaseError < StandardError
end
class SassC::NotRenderedError < SassC::BaseError
end
class SassC::InvalidStyleError < SassC::BaseError
end
class SassC::UnsupportedValue < SassC::BaseError
end
class SassC::SyntaxError < SassC::BaseError
end
class SassC::Engine
end
class SassC::Sass2Scss
end
