# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `simplecov-json` gem.
# Please instead update this file by running `bin/tapioca gem simplecov-json`.

class SimpleCov::Formatter::JSONFormatter
  def format(result); end
  def output_filename; end
  def output_filepath; end
  def output_message(result); end

  private

  def output_path; end
end
