# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/simplecov-json/all/simplecov-json.rbi
#
# simplecov-json-0.2.3

class SimpleCov::Formatter::JSONFormatter
end
