# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/simplecov-lcov/all/simplecov-lcov.rbi
#
# simplecov-lcov-0.8.0

module SimpleCovLcov
end
class SimpleCovLcov::Configuration
end
module SimpleCov
end
module SimpleCov::Formatter
end
class SimpleCov::Formatter::LcovFormatter
end
