# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/undercover/all/undercover.rbi
#
# undercover-0.4.4

module Undercover
end
class Undercover::LcovParseError < StandardError
end
class Undercover::LcovParser
end
class Undercover::Result
  extend Forwardable
end
module Undercover::CLI
end
class Undercover::Changeset
  extend Forwardable
  include Enumerable
end
class Undercover::Formatter
end
class Undercover::Options
end
class Undercover::Report
  extend Forwardable
end
