# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `yalphabetize` gem.
# Please instead update this file by running `bin/tapioca gem yalphabetize`.

# abAB
module Yalphabetize
  class << self
    def config; end
  end
end

class Yalphabetize::Aliaser
  # @return [Aliaser] a new instance of Aliaser
  def initialize(stream_node); end

  def call; end

  private

  # Returns the value of attribute aliases.
  def aliases; end

  def convert_node(child_node, anchor_node, alias_node); end
  def ensure_anchor_then_alias(node); end
  def nodes; end

  # Returns the value of attribute stream_node.
  def stream_node; end

  def swap(anchor_node, alias_node); end
end

class Yalphabetize::Alphabetizer
  # @return [Alphabetizer] a new instance of Alphabetizer
  def initialize(stream_node, order_checker_class:); end

  def call; end

  private

  def alphabetize_children(node, order_checker); end

  # Returns the value of attribute order_checker_class.
  def order_checker_class; end

  def pair_up_children(node); end

  # Returns the value of attribute stream_node.
  def stream_node; end

  def unpair_children(node); end
end

class Yalphabetize::CLI
  # @return [CLI] a new instance of CLI
  def initialize(argv); end

  def call; end

  private

  # Returns the value of attribute argv.
  def argv; end

  def options; end

  class << self
    def call(argv); end
  end
end

class Yalphabetize::FileYalphabetizer
  # @return [FileYalphabetizer] a new instance of FileYalphabetizer
  def initialize(file_path, **options); end

  def call; end

  private

  def alphabetize; end

  # Returns the value of attribute alphabetizer_class.
  def alphabetizer_class; end

  # Returns the value of attribute autocorrect.
  def autocorrect; end

  def autocorrect_file; end

  # Returns the value of attribute file_path.
  def file_path; end

  def handle_aliases; end

  # Returns the value of attribute logger.
  def logger; end

  # Returns the value of attribute offence_detector_class.
  def offence_detector_class; end

  # @return [Boolean]
  def offences?; end

  # Returns the value of attribute order_checker_class.
  def order_checker_class; end

  def print_to_log; end
  def reader; end

  # Returns the value of attribute reader_class.
  def reader_class; end

  def rewrite_yml_file; end
  def stream_node; end

  # Returns the value of attribute writer_class.
  def writer_class; end
end

class Yalphabetize::Logger
  # @return [Logger] a new instance of Logger
  def initialize(output = T.unsafe(nil)); end

  def final_summary; end
  def initial_summary(file_paths); end
  def log_correction(file_path); end
  def log_no_offence; end
  def log_offence(file_path); end

  # @return [Boolean]
  def offences?; end

  private

  def green(string); end

  # Returns the value of attribute inspected_count.
  def inspected_count; end

  def list_offences_color; end

  # Returns the value of attribute offences.
  def offences; end

  # Returns the value of attribute output.
  def output; end

  def puts_offence(file_path, status); end
  def red(string); end
  def with_color(color, string); end
  def yellow(string); end
end

Yalphabetize::Logger::DEFAULT_OUTPUT = T.let(T.unsafe(nil), IO)

class Yalphabetize::OffenceDetector
  # @return [OffenceDetector] a new instance of OffenceDetector
  def initialize(stream_node, order_checker_class:); end

  # @return [Boolean]
  def offences?; end

  private

  # @return [Boolean]
  def alphabetized?(node); end

  # @return [Boolean]
  def alphabetized_children?(node); end

  # @return [Boolean]
  def each_child_also_alphabetized?(children); end

  # Returns the value of attribute order_checker_class.
  def order_checker_class; end

  # Returns the value of attribute stream_node.
  def stream_node; end
end

class Yalphabetize::OptionParser
  class << self
    def parse!(argv); end
  end
end

Yalphabetize::OptionParser::PARSER = T.let(T.unsafe(nil), OptionParser)
module Yalphabetize::OrderCheckers; end

class Yalphabetize::OrderCheckers::AlphabeticalThenCapitalizedFirst < ::Yalphabetize::OrderCheckers::Base
  def compare(string, other_string); end
end

class Yalphabetize::OrderCheckers::AlphabeticalThenCapitalizedLast < ::Yalphabetize::OrderCheckers::Base
  def compare(string, other_string); end
end

class Yalphabetize::OrderCheckers::Base
  # @return [Boolean]
  def ordered?(string, other_string); end

  private

  def alphabetical_comparison(string, other_string); end

  class << self
    def new_for(node); end
  end
end

class Yalphabetize::OrderCheckers::CapitalizedFirstThenAlphabetical < ::Yalphabetize::OrderCheckers::Base
  def compare(string, other_string); end
end

class Yalphabetize::OrderCheckers::CapitalizedLastThenAlphabetical < ::Yalphabetize::OrderCheckers::Base
  def compare(string, other_string); end
end

class Yalphabetize::OrderCheckers::Custom < ::Yalphabetize::OrderCheckers::Base
  # @return [Custom] a new instance of Custom
  def initialize(allowed_order); end

  def compare(string, other_string); end

  private

  # Returns the value of attribute allowed_order.
  def allowed_order; end
end

Yalphabetize::OrderCheckers::TOKEN_MAPPING = T.let(T.unsafe(nil), Hash)
class Yalphabetize::ParsingError < ::Psych::SyntaxError; end

class Yalphabetize::Reader
  # @return [Reader] a new instance of Reader
  def initialize(path); end

  def to_ast; end

  private

  def file; end

  # Returns the value of attribute path.
  def path; end

  def stream_node; end
end

class Yalphabetize::SequenceIndenter
  # @return [SequenceIndenter] a new instance of SequenceIndenter
  def initialize(content); end

  def call; end

  private

  def block_sequence_nodes(node); end

  # Returns the value of attribute content.
  def content; end

  def file_lines; end
  def find_lines_to_indent; end
  def indent!; end
  def stream_node; end

  class << self
    def call(content); end
  end
end

class Yalphabetize::Version; end
Yalphabetize::Version::STRING = T.let(T.unsafe(nil), String)

class Yalphabetize::Writer
  # @return [Writer] a new instance of Writer
  def initialize(stream_node, path); end

  def call; end

  private

  def indent_sequences; end
  def new_file_content; end

  # Returns the value of attribute path.
  def path; end

  # Returns the value of attribute stream_node.
  def stream_node; end
end

Yalphabetize::Writer::MAX_LINE_WIDTH = T.let(T.unsafe(nil), Integer)

class Yalphabetize::Yalphabetizer
  # @return [Yalphabetizer] a new instance of Yalphabetizer
  def initialize(args, options); end

  def call; end

  private

  def alphabetizer_class; end

  # Returns the value of attribute args.
  def args; end

  def file_paths; end
  def file_yalphabetizer_class; end
  def final_log; end
  def finder; end
  def initial_log; end
  def logger; end
  def offence_detector_class; end
  def only_paths; end

  # Returns the value of attribute options.
  def options; end

  def order_checker_class; end
  def process_file(file_path); end
  def process_files; end
  def reader_class; end
  def writer_class; end

  class << self
    def call(args = T.unsafe(nil), options = T.unsafe(nil)); end
  end
end

class Yalphabetize::YamlFinder
  # @return [YamlFinder] a new instance of YamlFinder
  def initialize; end

  def paths(paths); end

  private

  # @return [Boolean]
  def exists?(path); end

  # Returns the value of attribute files.
  def files; end

  def files_in_dir(dir = T.unsafe(nil)); end
  def files_in_glob(glob); end

  # @return [Boolean]
  def glob?(path); end

  def process_paths(paths); end

  # @return [Boolean]
  def valid?(path); end

  # @return [Boolean]
  def yml?(path); end

  class << self
    def paths(only:, exclude:); end
  end
end

Yalphabetize::YamlFinder::YAML_EXTENSIONS = T.let(T.unsafe(nil), Array)
