// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CountdownController from "./countdown_controller"
import DynamicSelectController from "./dynamic_select_controller"
import NotificationController from "./notification_controller"
import Pwa__WebPushDemoController from "./pwa/web_push_demo_controller"
import Pwa__WebPushSubscriptionController from "./pwa/web_push_subscription_controller"
import SearchController from "./search_controller"

application.register("countdown", CountdownController)
application.register("dynamic-select", DynamicSelectController)
application.register("notification", NotificationController)
application.register("pwa--web-push-demo", Pwa__WebPushDemoController)
application.register("pwa--web-push-subscription", Pwa__WebPushSubscriptionController)
application.register("search", SearchController)
