ActiveRecordDoctor.configure do
  # Global settings affect all detectors.
  global :ignore_tables, [
    # Ignore internal Rails-related tables.
    "ar_internal_metadata",
    "schema_migrations",
    "action_text_rich_texts",
    "active_storage_attachments",
    "active_storage_blobs",
    "solid_cable_messages",
    "solid_queue_blocked_executions",
    "solid_queue_claimed_executions",
    "solid_queue_failed_executions",
    "solid_queue_jobs",
    "solid_queue_pauses",
    "solid_queue_processes",
    "solid_queue_ready_executions",
    "solid_queue_recurring_executions",
    "solid_queue_recurring_tasks",
    "solid_queue_scheduled_executions",
    "solid_queue_semaphores",

    # Add project-specific tables here.
    /\Aff_/,
    /\Amotor_/,
    "auto_entry_status",
    "auto_shipping_status",
    "pending_retirements",
    "horse_racehorses_mv",
    "horse_training_schedules_mv",
    "user_alerts",
    "user_preferences"
  ]

  global :ignore_models, [
    "ActionMailbox::InboundEmail",
    "ActionText::EncryptedRichText",
    "ActionText::RichText",
    "ActiveStorage::Attachment",
    "ActiveStorage::Blob",
    "ActiveStorage::VariantRecord",
    "SolidCable::Message",
    "SolidCache::Entry",
    "SolidQueue::BlockedExecution",
    "SolidQueue::ClaimedExecution",
    "SolidQueue::FailedExecution",
    "SolidQueue::Job",
    "SolidQueue::Pause",
    "SolidQueue::Process",
    "SolidQueue::ReadyExecution",
    "SolidQueue::RecurringExecution",
    "SolidQueue::RecurringTask",
    "SolidQueue::ScheduledExecution",
    "SolidQueue::Semaphore",
    "Audited::Audit",
    "Legacy::Activity",
    "Legacy::ActivityPoint",
    "Legacy::AdminSetting",
    "Legacy::Alert",
    "Legacy::Auction",
    "Legacy::AuctionHorse",
    "Legacy::AutoEntryStatus",
    "Legacy::AutoShippingStatus",
    "Legacy::Boarding",
    "Legacy::BreedRanking",
    "Legacy::BreedersCupStallion",
    "Legacy::BreedersSeriesNomination",
    "Legacy::Breeding",
    "Legacy::Claim",
    "Legacy::ColorWar",
    "Legacy::ColorWarActivity",
    "Legacy::ColorWarEntry",
    "Legacy::ColorWarGuess",
    "Legacy::ColorWarGuessOrder",
    "Legacy::ColorWarPrize",
    "Legacy::ColorWarPrizeOffer",
    "Legacy::ColorWarRaceVote",
    "Legacy::ColorWarResult",
    "Legacy::ColorWarScore",
    "Legacy::ColorWarSecret",
    "Legacy::ColorWarSetting",
    "Legacy::ColorWarSignup",
    "Legacy::ColorWarTeam",
    "Legacy::Comment",
    "Legacy::DeletedStable",
    "Legacy::Donation",
    "Legacy::Equipment",
    "Legacy::Farm",
    "Legacy::FoalRecord",
    "Legacy::FrequentlyAskedQuestion",
    "Legacy::FrequentlyAskedQuestionAnswer",
    "Legacy::FrequentlyAskedQuestionArticle",
    "Legacy::FrequentlyAskedQuestionCategory",
    "Legacy::FrequentlyAskedQuestionQuestion",
    "Legacy::FutureEntry",
    "Legacy::FutureEvent",
    "Legacy::FutureShipping",
    "Legacy::Horse",
    "Legacy::HorseBreedRanking",
    "Legacy::HorseBroodmareSireBreedRanking",
    "Legacy::HorseColor",
    "Legacy::HorseComment",
    "Legacy::HorseEvent",
    "Legacy::HorseHistory",
    "Legacy::HorseInjury",
    "Legacy::HorseJockey",
    "Legacy::HorseLatestClaimingRace",
    "Legacy::HorseLatestInjury",
    "Legacy::HorseMarking",
    "Legacy::HorseOfTheYearCategory",
    "Legacy::HorseOfTheYearWinner",
    "Legacy::HorseSale",
    "Legacy::HorseShipping",
    "Legacy::HorseStatus",
    "Legacy::HorseTitle",
    "Legacy::Injury",
    "Legacy::InjuryType",
    "Legacy::Jockey",
    "Legacy::JockeyInstruction",
    "Legacy::JockeyLine",
    "Legacy::JockeyRecord",
    "Legacy::JockeyStatus",
    "Legacy::JumpTrial",
    "Legacy::Lease",
    "Legacy::MarkingImage",
    "Legacy::Nomination",
    "Legacy::NominationRace",
    "Legacy::NominationSupplemental",
    "Legacy::Odd",
    "Legacy::Pedigree",
    "Legacy::PendingRetirement",
    "Legacy::QualifiedHorse",
    "Legacy::QualifiedRace",
    "Legacy::Race",
    "Legacy::RaceAge",
    "Legacy::RaceEntry",
    "Legacy::RaceGrade",
    "Legacy::Racetrack",
    "Legacy::Record",
    "Legacy::RaceRecord",
    "Legacy::RaceRecordAllowance",
    "Legacy::RaceRecordLifetime",
    "Legacy::RaceResult",
    "Legacy::RaceResultHorse",
    "Legacy::RaceType",
    "Legacy::Shipping",
    "Legacy::Skin",
    "Legacy::SpeedRecord",
    "Legacy::StableNote",
    "Legacy::StableRaceRecord",
    "Legacy::TrackCondition",
    "Legacy::TrackType",
    "Legacy::TrackWeather",
    "Legacy::TrainingSchedule",
    "Legacy::TrainingScheduleDetail",
    "Legacy::TrainingScheduleHorse",
    "Legacy::TripleCrownTitle",
    "Legacy::TripleCrownWinner",
    "Legacy::User",
    "Legacy::UserAlert",
    "Legacy::UserColor",
    "Legacy::UserPreference",
    "Legacy::UserStyle",
    "Legacy::UserWarning",
    "Legacy::Weather",
    "Legacy::Workout",
    "Legacy::WorkoutBonus",
    "Legacy::WorkoutType",
    "Legacy::ViewRacehorses",
    "Legacy::ViewTrainingSchedules",
    "Motor::Alert",
    "Motor::AlertLock",
    "Motor::ApiConfig",
    "Motor::Config",
    "Motor::Dashboard",
    "Motor::Form",
    "Motor::Note",
    "Motor::NoteTag",
    "Motor::NoteTagTag",
    "Motor::Notification",
    "Motor::Reminder",
    "Motor::Query",
    "Motor::Resource",
    "Motor::Tag",
    "Motor::Taggable",
    "Motor::TaggableTag"
  ]

  detector :incorrect_dependent_option,
    ignore_models: [
      "Motor::Alert",
      "Motor::Dashboard",
      "Motor::Form",
      "Motor::Query",
      "Motor::Tag"
    ]

  detector :missing_non_null_constraint,
    ignore_tables: [
      "ff_horses",
      "ff_trackdata",
      "ff_training_schedules",
      "ff_training_schedule_details",
      "ff_training_schedule_horses",
      "ff_users"
    ]

  detector :missing_presence_validation,
    ignore_attributes: [
      "Account::Stable.bred_horses_count",
      "Account::Stable.horses_count",
      "Account::Stable.unborn_horses_count",
      "Account::User.encrypted_password",
      "Account::User.failed_attempts",
      "Account::User.sign_in_count",
      "Horses::Horse.foals_count",
      "Horses::Horse.unborn_foals_count",
      "Horses::Stallion.foals_count",
      "Horses::Stallion.unborn_foals_count",
      "Racing::TrainingSchedule.horses_count",
      "Racing::TrainingSchedule.sunday_activities",
      "Racing::TrainingSchedule.monday_activities",
      "Racing::TrainingSchedule.tuesday_activities",
      "Racing::TrainingSchedule.wednesday_activities",
      "Racing::TrainingSchedule.thursday_activities",
      "Racing::TrainingSchedule.friday_activities",
      "Racing::TrainingSchedule.saturday_activities"
    ]

  detector :missing_unique_indexes,
    ignore_columns: [
      "Account::User(username)" # includes discarded_at WHERE
    ]

  detector :unindexed_deleted_at,
    ignore_indexes: [
      "index_users_on_lowercase_username" # includes lowercase username
    ]

  detector :table_without_timestamps,
    ignore_tables: [
      "active_storage_variant_records",
      "data_migrations"
    ]

  detector :missing_foreign_keys,
    ignore_associations: [
      "Racing::AnnualRaceRecord.horse",
      "Racing::LifetimeRaceRecord.horse"
    ]
end

