plugins:
  bundler-audit:
    enabled: true
  haml-lint:
    enabled: true
exclude_patterns:
  - ".git-hooks"
  - "config/"
  - "db/"
  - "**/node_modules/"
  - "**/spec/"
  - "**/*.d.ts"
  - "**/vendor/"
