plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  editorconfig:
    enabled: true
  fixme:
    enabled: true
  haml-lint:
    enabled: true
  reek:
    enabled: true
  shellcheck:
    enabled: true
  stylelint:
    enabled: true
exclude_patterns:
  - ".git-hooks/"
  - "app/services/migrate_*_service.rb"
  - "config/"
  - "db/"
  - "**/node_modules/"
  - "**/spec/"
  - "**/*.d.ts"
  - "**/vendor/"
