e
PreCommit:
  ALL:
    on_warn: fail
    exclude:
      - 'node_modules/**/*'
      - 'vendor/**/*'

  BundleCheck:
    enabled: true

  MergeConflicts:
    enabled: true
  RailsSchemaUpToDate:
    enabled: true
  TrailingWhitespace:
    enabled: true
  YamlSyntax:
    enabled: true
    exclude:
      - .semaphore/semaphore.yml

