require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sorbet

inherit_gem:
  rubocop-rails: config/default.yml
  rubocop-sorbet: config/default.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - "bin/**/*"
    - "db/**/schema.rb"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - ".simplecov"

  NewCops: enable
  TargetRubyVersion: 3.1

Bundler/OrderedGems:
  Enabled: true
Layout/LineLength:
  Max: 120
  Exclude:
    - "config/initializers/**/*.rb"
    - "config/routes.rb"
    - "db/migrate/**/*.rb"
    - "Gemfile"
Layout/LineEndStringConcatenationIndentation:
  Enabled: true
  EnforcedStyle: aligned
Lint/SymbolConversion:
  Enabled: true
  EnforcedStyle: strict
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space
Lint/InterpolationCheck:
  Enabled: false
Lint/SuppressedException:
  Exclude:
    - "Rakefile"
Metrics/AbcSize:
  Exclude:
    - "db/migrate/**/*.rb"
Metrics/BlockLength:
  Exclude:
    - "Gemfile*"
    - "config/**/*.rb"
    - "db/migrate/**/*.rb"
    - "lib/tasks/**/*.rake"
Metrics/MethodLength:
  Exclude:
    - "db/migrate/**/*.rb"
Rails/Output:
  Exclude:
    - "db/seeds.rb"

Sorbet/FalseSigil:
  Exclude:
    - 'config/**/*.rb'
    - 'db/**/*.rb'
    - 'lib/**/*.rake'
    - 'app/validators/**/*.rb'


Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false
Style/EndlessMethod:
  Enabled: true
  EnforcedStyle: allow_single_line
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
  AutoCorrect: true
Style/MutableConstant:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  Exclude:
    - Dangerfile
Style/SignalException:
  Enabled: true
  Exclude:
    - Dangerfile
