inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - rubocop-graphql
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  rubocop-rails: config/default.yml
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-rails: config/base.yml

inherit_from:
  - .rubocop_strict.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - "bin/**/*"
    - "db/**/schema.rb"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - ".simplecov"
    - "app/models/legacy_*.rb"
  NewCops: enable
  TargetRubyVersion: 3.2

Bundler/OrderedGems:
  Enabled: true
Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods
Layout/LineEndStringConcatenationIndentation:
  Enabled: true
  EnforcedStyle: aligned
Layout/LineLength:
  Max: 120
  Exclude:
    - "config/initializers/**/*.rb"
    - "config/routes.rb"
    - "db/migrate/**/*.rb"
    - "Gemfile"
    - "app/models/legacy/*.rb"
    - "app/services/migrate_legacy_*.rb"
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space
Layout/TrailingEmptyLines:
  Enabled: true
  EnforcedStyle: final_blank_line
Lint/InterpolationCheck:
  Enabled: false
Lint/SuppressedException:
  Exclude:
    - "Rakefile"
Lint/SymbolConversion:
  Enabled: true
  EnforcedStyle: strict
Metrics/AbcSize:
  Exclude:
    - "db/data/**/*.rb"
    - "db/migrate/**/*.rb"
Metrics/BlockLength:
  Exclude:
    - "Gemfile*"
    - "Guardfile"
    - "config/**/*.rb"
    - "db/migrate/**/*.rb"
    - "lib/tasks/**/*.rake"
Metrics/ClassLength:
  Exclude:
    - "db/migrate/**/*.rb"
Metrics/MethodLength:
  Exclude:
    - "db/data/**/*.rb"
    - "db/migrate/**/*.rb"
    - "app/models/legacy/*.rb"
Naming/InclusiveLanguage:
  Enabled: true
Rails/Output:
  Exclude:
    - "db/seeds.rb"
Style/ClassAndModuleChildren:
  EnforcedStyle: nested
Style/Documentation:
  Enabled: false
Style/EndlessMethod:
  Enabled: true
  EnforcedStyle: allow_single_line
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
  AutoCorrect: true
Style/MutableConstant:
  Enabled: false
Style/SignalException:
  Enabled: true
  Exclude:
    - Dangerfile
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  Exclude:
    - Dangerfile
