require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sorbet

inherit_gem:
  rubocop-rails: config/default.yml
  rubocop-sorbet: config/default.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/schema.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
  NewCops: pending
  TargetRubyVersion: 3.1
Bundler/OrderedGems:
  Enabled: true
Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/**/*.rb'
    - 'config/routes.rb'
    - 'db/migrate/**/*.rb'
    - 'Gemfile'
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space
Lint/InterpolationCheck:
  Enabled: false
Lint/SuppressedException:
  Exclude:
    - 'Rakefile'
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*.rb'
Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'
    - 'db/migrate/**/*.rb'
    - 'lib/tasks/**/*.rake'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*.rb'
Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/users/devise_controller.rb'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
  AutoCorrect: true
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  Exclude:
    - Dangerfile
Style/SignalException:
  Enabled: true
  Exclude:
    - Dangerfile
