require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/schema.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
  NewCops: disable
  TargetRubyVersion: 3.1
Bundler/OrderedGems:
  Enabled: true
Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/simple_form_bulma.rb'
    - 'config/routes.rb'
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space
Lint/InterpolationCheck:
  Enabled: false
Lint/SuppressedException:
  Exclude:
    - 'Rakefile'
Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'
    - 'db/migrate/**/*.rb'
    - 'lib/tasks/**/*.rake'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*.rb'
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
