require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails
  - rubocop-rake

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/schema.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
  DisplayCopNames: true
  NewCops: disable
  TargetRubyVersion: 3.1

Bundler/OrderedGems:
  Enabled: true

Layout/LineLength:
  Max: 120

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space

Lint/SuppressedException:
  Exclude:
    - 'Rakefile'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
