# Whether to ignore frontmatter at the beginning of Slim documents for
# frameworks such as Jekyll/Middleman
skip_frontmatter: false

linters:
  CommentControlStatement:
    enabled: true

  ConsecutiveControlStatements:
    enabled: true
    max_consecutive: 2

  ControlStatementSpacing:
    enabled: false

  EmbeddedEngines:
    enabled: false
    forbidden_engines: [ ]

  EmptyControlStatement:
    enabled: true

  EmptyLines:
    enabled: true

  FileLength:
    enabled: false
    max: 300

  InstanceVariables:
    enabled: false
    include:
      # Include only partial templates by default
      - app/views/**/_*.html.slim

  LineLength:
    enabled: true
    max: 120

  RedundantDiv:
    enabled: true

  RuboCop:
    enabled: true

  StrictLocalsMissing:
    enabled: false
    include:
      # Include only Rails partial templates by default
      - app/views/**/_*.html.slim

  Tab:
    enabled: true

  Tag:
    enabled: false
    forbidden_tags: [ ]

  TagAttribute:
    enabled: false
    forbidden_attributes: [ ]

  TagCase:
    enabled: true

  TrailingBlankLines:
    enabled: true

  TrailingWhitespace:
    enabled: true

  QuoteConsistency:
    enabled: false

  Zwsp:
    enabled: false
