name: final_furlong

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"
    container_name: app
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - .:/app
      - ./bundle_cache:/bundle
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet

  db:
    image: postgres:17
    container_name: db
    restart: on-failure:5
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "pgdata:/var/lib/postgres/data"
    ports:
      - "5432:${DATABASE_PORT}"
    networks:
      - appnet

  good_job:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec good_job start
    container_name: jobs
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - .:/app
      - ./bundle_cache:/bundle
    depends_on:
      - app
    networks:
      - appnet

volumes:
  pgdata:
  bundle_cache:

networks:
  appnet:
    driver: bridge
