shared:
  statuses:
    - pending
    - approved
    - bred
    - denied
  min_age: 4
  stud_breeders_cup_nomination_deadline_month: 2
  stud_breeders_cup_nomination_deadline_day: 14
  birth_events:
    - twins_alive
    - twins_death
    - stillborn
    - death
    - birth
  mares_per_slot: 2
  slots:
    [
      { month: 2, start: 15, end: 22 },
      { month: 2, start: 22, end: 29 },
      { month: 3, start: 1, end: 10 },
      { month: 3, start: 11, end: 20 },
      { month: 3, start: 21, end: 31 },
      { month: 4, start: 1, end: 15 },
      { month: 4, start: 16, end: 30 },
      { month: 5, start: 1, end: 15 },
      { month: 5, start: 16, end: 31 },
      { month: 6, start: 1, end: 15 },
      { month: 6, start: 16, end: 30 },
      { month: 7, start: 1, end: 15 },
      { month: 7, start: 16, end: 31 },
      { month: 8, start: 1, end: 15 },
      { month: 8, start: 16, end: 31 }
    ]
