shared:
  currency: $
  eclipse_award_voting_days: 21
  notification_expiration_after_reading: 30
  online_minutes: 15
  title: Final Furlong
  stable: Final Furlong
  username: FFadmin
  username_minimum_length: 3
  activity_types:
    - color_war
    - auction
    - selling
    - buying
    - breeding
    - claiming
    - entering
    - redeem
  eclipse_awards:
    - 2 Year Old Colt
    - 2 Year Old Filly
    - 3 Year Old Colt
    - 3 Year Old Filly
    - Older Horse
    - Older Mare
    - Sprinter
    - Classic Horse
    - Endurance Horse
    - Turf Horse
    - Turf Mare
    - Steeplechase Colt
    - Steeplechase Filly
    - Steeplechase Horse
    - Steeplechase Mare
    - Horse of the Year
    - Stable of the Year
    - Breeder of the Year
    - Sire of the Year
