shared:
  claiming_deadline_days: 1
  entry_open_days: 8
  entry_deadline_days: 2
  entry_fee_percent: 0.05
  entry_limit_2yo: 1
  entry_limit_older: 2
  entry_limit_increase_final_day: 1
  entry_limit_overall: 14
  future_race_limit: 5
  future_race_max_days: 90
  future_race_max_schedule_days: 180
  future_entry_limit_2_days_out: 14
  future_entry_limit_8_days_out: 7
  max_racing_age: 10
  minimum_distance: 5.0
  maximum_distance: 24.0
  minimum_energy: -100
  maximum_energy: 100
  minimum_fitness: 20
  maximum_fitness: 120
  minimum_xp: 0
  maximum_xp: 100
  minimum_horses: 6
  minimum_horses_stakes: 10
  minimum_energy_racefiller: 80
  min_races_to_retire: 10
  min_stud_stakes_wins: 7
  min_stud_stakes_places: 3
  min_stud_grade_1_stakes_wins: 1
  min_stud_grade_1_stakes_places: 2
  travel_deadline_days: 1
  racehorse_types:
    - flat
    - jump
  styles:
    - leading
    - off_pace
    - midpack
    - closing
  horse_titles:
    - Final Furlong
    - World
    - International
    - National
    - Grand
    - Normal
  title_points:
    final_furlong: 1500
    world: 1000
    international: 750
    national: 500
    grand: 300
    normal: 100
  all_types:
    - maiden
    - claiming
    - starter_allowance
    - nw1_allowance
    - nw2_allowance
    - nw3_allowance
    - allowance
    - stakes
  claiming_types:
    - claiming
    - starter_allowance
  qualified_types:
    - maiden
    - nw1_allowance
    - nw2_allowance
    - nw3_allowance
  non_qualified_types:
    - allowance
    - stakes
  surfaces:
    - dirt
    - turf
    - steeplechase
  conditions:
    - fast
    - good
    - slow
    - wet
  ages:
    - "2"
    - "2+"
    - "3"
    - "3+"
    - "4"
    - "4+"
  filter_ages:
    - "2yo"
    - "3yo"
    - "4yo+"
  filter_injuries:
    - past
    - present
    - none
  filter_entries:
    - current
    - scheduled
    - none
  grades:
    - Ungraded
    - Grade 3
    - Grade 2
    - Grade 1
  letter_grades:
    - A
    - B
    - C
    - D
    - F
  purses:
    - 0.6
    - 0.2
    - 0.1
    - 0.07
    - 0.03
  points:
    stakes:
      - 42
      - 21
      - 10
      - 7
    allowance:
      - 10
      - 7
      - 3
    claiming:
      - 2
      - 1
    maiden:
      - 2
      - 1
  weights:
    apprentice_jockey_bonus: 3
    female_bonus: 3
    younger_bonus: 2
    maiden_bonus_open_allowance: 3
    maiden_bonus_non_open_allowance: 2
    maiden_bonus_stakes: 5
    maiden: 122
    claiming_15000: 122
    claiming_40000: 126
    claiming: 130
    starter_allowance: 124
    nw1_allowance: 126
    nw2_allowance: 128
    nw3_allowance: 130
    allowance: 132
    stakes: 134
    stakes_handicap_min: 108
    stakes_handicap_max: 150
