shared:
  max_racing_age: 10
  minimum_distance: 5.0
  maximum_distance: 24.0
  minimum_energy: -100
  maximum_energy: 100
  minimum_fitness: 20
  maximum_fitness: 120
  minimum_xp: 0
  maximum_xp: 100
  racehorse_types:
    - flat
    - jump
  styles:
    - leading
    - off_pace
    - midpack
    - closing
  horse_titles:
    - Final Furlong
    - World
    - International
    - National
    - Grand
    - Normal
  title_points:
    final_furlong: 1500
    world: 1000
    international: 750
    national: 500
    grand: 300
    normal: 100
  all_types:
    - maiden
    - claiming
    - starter_allowance
    - nw1_allowance
    - nw2_allowance
    - nw3_allowance
    - allowance
    - stakes
  claiming_types:
    - claiming
    - starter_allowance
  qualified_types:
    - maiden
    - nw1_allowance
    - nw2_allowance
    - nw3_allowance
  non_qualified_types:
    - allowance
    - stakes
  surfaces:
    - dirt
    - turf
    - steeplechase
  conditions:
    - fast
    - good
    - slow
    - wet
  ages:
    - "2"
    - "2+"
    - "3"
    - "3+"
    - "4"
    - "4+"
  filter_ages:
    - "2yo"
    - "3yo"
    - "4yo+"
  filter_injuries:
    - past
    - present
    - none
  grades:
    - Ungraded
    - Grade 3
    - Grade 2
    - Grade 1
  letter_grades:
    - A
    - B
    - C
    - D
    - F
  purses:
    - 0.6
    - 0.2
    - 0.1
    - 0.07
    - 0.03
  points:
    stakes:
      - 42
      - 21
      - 10
      - 7
    allowance:
      - 10
      - 7
      - 3
    claiming:
      - 2
      - 1
    maiden:
      - 2
      - 1
