# ruby-cache: &ruby-cache
  # id: ruby
  # backend: s3
  # key: "v1.3-cache-{{ id }}-{{ runner.os }}-{{ checksum 'air-dx/Gemfile.lock' }}-test"
  # restore-keys:
    # - "v1.3-cache-{{ id }}-{{ runner.os }}-"
    # - "v1.3-cache-{{ id }}-"
  # pr: true
  # s3:
    # bucket: nua-buildkite-cache
  # paths:
    # - air-dx/vendor/bundle
  # compress: true

# node-cache: &node-cache
  # id: node
  # backend: s3
  # key: "v1.3-cache-{{ id }}-{{ runner.os }}-{{ checksum 'air-dx/yarn.lock' }}-test"
  # restore-keys:
    # - "v1.3-cache-{{ id }}-{{ runner.os }}-"
    # - "v1.3-cache-{{ id }}-"
  # pr: true
  # s3:
    # bucket: nua-buildkite-cache
  # paths:
    # - node_modules
  # compress: true

env:
  RAILS_ENV: test
  DOCKER_IMAGE_NAME: ff-ci
  DOCKER_WORKING_DIR: /app
  DOCKER_ENTRYPOINT_PATH: ./docker/entrypoint-ci.sh
  ASSETS_PRECOMPILED: true

docker-compose: &docker-compose
  args:
    - GITHUB_TOKEN
    - CUID

steps:
  - label: ":docker: Build"
    key: "docker-build"
    plugins:
      - docker-compose#v3.9.0:
          <<: *docker-compose
          build: app

  - label: ":bundler: Installing Dependencies"
    command: "./scripts/dependencies_gems.sh"
    key: "dependencies"
    depends_on:
      - "docker-build"
    plugins:
      - docker-compose#v3.9.0:
          <<: *docker-compose
          run: app
      - gencer/cache#v2.4.8: *ruby-cache

  - label: ":webpack: Precompiling Assets"
    command: "./scripts/assets.sh"
    depends_on:
      - "dependencies"
    key: "assets"
    plugins:
      - docker-compose#v3.9.0:
          <<: *docker-compose
          run: app
          mount-buildkite-agent: true
          volumes:
            - ${BUILDKITE_AGENT_BINARY_PATH:-/usr/bin/buildkite-agent}:/usr/bin/buildkite-agent
      - gencer/cache#v2.4.8: *ruby-cache
      - gencer/cache#v2.4.8: *node-cache

  - label: ":rspec: RSpec"
    command: "./scripts/rspec.sh"
    depends_on:
      - "assets"
    key: "rspec"
    artifact_paths:
      - "app/tmp/capybara/*"
      - "app/log/*.log"
    plugins:
      - docker-compose#v3.9.0:
          <<: *docker-compose
          run: app
          mount-buildkite-agent: true
          volumes:
            - ${BUILDKITE_AGENT_BINARY_PATH:-/usr/bin/buildkite-agent}:/usr/bin/buildkite-agent
