# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Shared::ErrorMessagesComponent`.
# Please instead update this file by running `bin/tapioca dsl Shared::ErrorMessagesComponent`.

class Shared::ErrorMessagesComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
