class UpdateToUuid7Ids < ActiveRecord::Migration[8.0]
  def up
    require "securerandom"

    def update_ids(model_class)
      ActiveRecord::Base.transaction do
        records = if model_class.column_names.include?("seq")
          # Sort by the 'seq' column if the model has it, as it describes the sequence of the records
          model_class.order(:seq)
        elsif model_class.column_names.include?("created_at")
          # Sort by the 'created_at' column, which is automatically generated by Ruby on Rails with 't.timestamps'
          model_class.order(:created_at)
        else
          model_class.order(:id)
        end

        records.each do |record|
          new_id = SecureRandom.uuid_v7
          model_class.where(id: record.id).update_all(id: new_id)
        end
      end
    end

    Rails.application.eager_load!

    models = ApplicationRecord.descendants
    puts models.inspect # Show all models

    models.each do |model|
      if model.column_for_attribute(:id)&.type == :uuid
        puts "Updating IDs for #{model.name}..."
        update_ids(model)
      else
        puts "Skipping #{model.name} (id is not uuid)"
      end
    end
  end

  def down
    raise ActiveRecord::IrreversibleMigration
  end
end

