inherit_from:
  - '../.rubocop.yml'

Capybara/NegationMatcher:
  EnforcedStyle: not_to

Layout/LineLength:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/BeEq:
  Enabled: true

RSpec/BeEql:
  Enabled: true

RSpec/BeNil:
  Enabled: true

RSpec/DescribedClass:
  SkipBlocks: true

RSpec/DescribedClassModuleWrapping:
  Enabled: true

RSpec/EmptyLineAfterExample:
  AllowConsecutiveOneLiners: true

RSpec/ExampleLength:
  Max: 10

RSpec/ExcessiveDocstringSpacing:
  Enabled: true

RSpec/IdenticalEqualityAssertion:
  Enabled: true

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 4

RSpec/NestedGroups:
  AllowedGroups: [ describe ]
